In [2]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit
warnings.filterwarnings("ignore")
from sympy import *

### The Quantum Object 


### Bra-Ket Notation

In [3]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

The base quantum object is a **bra** vector denoted by $\langle \psi|$

This is the equivalent of a 1x1 matrix with zero as the only entry.

Creating a bra vector with data using list comp:

In [4]:
x= Qobj([[x for x in range(4)]])
x

Quantum object: dims = [[1], [4]], shape = (1, 4), type = bra
Qobj data =
[[0. 1. 2. 3.]]

In [26]:
x.dims

[[1], [4]]

In [5]:
y = Qobj([[y] for y in range(4)])
y

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [2.]
 [3.]]

In [27]:
y.dims

[[4], [1]]

### Dot Product

***Magnitude***

In [6]:
num = x * y
num

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[14.]]

In [7]:
abs_x = (x * x.trans()).data[0]

In [8]:
abs_y = (y.trans() * y).data[0]

In [12]:
denom = (abs_x * abs_y).data[0]

In [13]:
denom = np.real(denom)
denom

196.0

***Angle***

In [14]:
theta = np.arccos((x.trans() * y) / (denom))

TypeError: Incompatible Qobj shapes

In [ ]:
np.real(theta)

A **ket** vector, represented by $|\psi\rangle$ is the equivalent of a column vector. In this notation, we have created a 1x5 column vector.

- qtip rundown

- Bra / Ket notation

- Commutators

- Spin

- tunneling

- Hilbert Space

- Back prop parameters


A random vector, really an **operator**

In [ ]:
r = np.random.rand(4,4)
r

In [ ]:
r = Qobj(r)
r

In [ ]:
r.matrix_element(x, y)
r.matrix_element?

$$\langle x|r|y\rangle$$

### Creating a Hilbert Space

### fock state operator

- The equivalent of a particle selector operator $\hat{N}_{k}$ where $\sum_{i}\hat{N}_{k_{i}}$ = $\hat{N}$ (the total number of particles in a system).

In [ ]:
basis(10, 3)

In multi-dimensional space:

In [ ]:
fock_dm(10, 3)

### Operator Example

***Destruction Operator***

The lowering operator, removes elements of a matrix below a particular ground state. It is particularly useful for the case of the Quantum Harmonic Oscillator.

In [17]:
d = destroy(4)

In [18]:
d.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

***Sparse matrices are the default storage type***

In [19]:
d

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

### Matrix Mathematics 

- Adding constants

In [20]:
d + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

adding or subtracting a constant *a* is the equivalent of adding/subtracting $a\hat{I}$ where $\hat{I}$ is the identity matrix.

- Multiplication follows the normal definition of the inner (dot) product

In [21]:
spin_operator = sigmax()

In [22]:
spin_operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [23]:
spin_operator * spin_operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In Bra-Ket notation the inner product is simplified:

$$\langle\psi_{a} | \psi_{b}\rangle$$

Represents the inner product of two vectors, a **bra** on the left and a **ket** on the right.

- Chained dot product

In [24]:
d ** 3

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

Is the equivalent of:

In [25]:
d * d * d

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

### Operations on Quantum Objects

Support exists for a variety of handy linear algebra functions such as eigenvalues, eigenvectors, diagonals, traces, hermitian conjugation etc.

In [ ]:
space = basis(8, 1)
space

The adjoint operator $\dagger\$, often referred to as the **dagger** operator takes the transpose of a matrix.

In [ ]:
space.dag()

- Diagonals

In [ ]:
coherent_density_matrix = coherent_dm(5,1)
coherent_density_matrix

In [ ]:
coherent_density_matrix.diag().sum()

- Ladder op example

#### Distance metrics for determining how close to density matrix distributions are to each other

- Trace Distance

- fidelity

- Hilbert-Schmidt distance

- Bures-distance

- Bures angle

- Hellinger distance

***Comparisons of train/test splits for distributions?***

### Quantum Mechanics:

Easy stuff first! 

#### The Time Dependent Schroedinger Equation:

$$i\hbar \frac{\partial \Psi}{\partial t} = -\frac{\hbar^2}{2m}
\frac{\partial^2 \Psi}{\partial x^2} + V \Psi$$

This equation is a PDE, where the wavefunction $\Psi(\hat{r}, t)$ is function of both position and time. 

The Hamiltonian operator $\hat{H}$ represents the classical total energy of a quantum system (Kinetic + Potential).

In operator form:

$$\hat{H}\Psi=E\ \Psi$$

By assuming that the wave function can be expressed as the product of two functions, $\psi(\hat{r})$ and $\phi(t)$, separation of variables can be employed and the separation constant C of the time independent equation represents the allowed energies (eigenenergies) of the operator $\hat{H}$.

It is often favorable to represent the operator $\hat{H}$ in terms of its **eigenvectors** where the resultant matrix consists of all off-diagonal elements equal to zero and the diagonal formed by the eigenenergies.

The eigenstates of the 1-Dimension Quantum Well are a set of even and odd solutions given the quantum number **n**:

$$\psi_{n}(x) = \sqrt{\frac{2}{L}}\sin(k_{n}x)
        for\ n\ even\$$
        
        
$$\psi_{n}(x) = \sqrt{\frac{2}{L}}\cos(k_{n}x)
        for\ n\ odd\$$
        
        
$$k_{n}=\frac{n\pi}{L}$$

In [ ]:
[y for y in n(0,1,501)]

In [ ]:
#plot the eigenstates of a 1-d quantum well
L = 1e-9
for n in range(1, 4, 1):
    p = sns.lineplot(
        x=[x for x in np.linspace(0, 2 * np.pi, 100)],
        y=[wave_function(n).calc(x) for x in np.linspace(0, 2 * np.pi, 100)],
        label=f'Eigenstate-{n}')
    p.set_xticklabels(['' for x in p.get_xticks()])
    p.set_yticklabels(['' for x in p.get_yticks()])

In [ ]:
class wave_function():
    def __init__(self, n=2, L=1):
        self.n = n
        self.L = L
        self.k = (n * np.pi)/L
    def calc(self, x):
        if self.n % 2 == 0:
            return np.sqrt(2/self.L)*np.sin(self.k*x)
        else:
            return np.sqrt(2/self.L)*np.cos(self.k*x)
        

In [ ]:
wave_function(n=5).calc(np.pi)

In [ ]:
x

In [ ]:
x.calc(np.pi)