In [71]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### The Quantum Object 


### Bra-Ket Notation

In [72]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

The base quantum object is a **bra** vector denoted by $\langle \psi|$

This is the equivalent of a 1x1 matrix with zero as the only entry.

Creating a bra vector with data using list comp:

In [73]:
Qobj([[x for x in range(5)]])

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[0. 1. 2. 3. 4.]]

In [74]:
Qobj([[x] for x in range(5)])

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]]

A **ket** vector, represented by $|\psi\rangle$ is the equivalent of a column vector. In this notation, we have created a 1x5 column vector.

- qtip rundown

- Bra / Ket notation

- Commutators

- Spin

- tunneling

- Hilbert Space

- Back prop parameters


A random vector, really an **operator**

In [75]:
r = np.random.rand(4,4)
r

array([[0.30541738, 0.91961236, 0.0931158 , 0.8698288 ],
       [0.45106397, 0.77105709, 0.23386503, 0.38193948],
       [0.54561342, 0.97050744, 0.33161566, 0.33388215],
       [0.06361814, 0.77580532, 0.38979033, 0.49871187]])

In [76]:
Qobj(r)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.30541738 0.91961236 0.0931158  0.8698288 ]
 [0.45106397 0.77105709 0.23386503 0.38193948]
 [0.54561342 0.97050744 0.33161566 0.33388215]
 [0.06361814 0.77580532 0.38979033 0.49871187]]

### Creating a Hilbert Space

### fock state operator

- The equivalent of a particle selector operator $\hat{N}_{k}$ where $\sum_{i}\hat{N}_{k_{i}}$ = $\hat{N}$ (the total number of particles in a system).

In [77]:
basis(10, 3)

Quantum object: dims = [[10], [1]], shape = (10, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In multi-dimensional space:

In [78]:
fock_dm(10, 3)

Quantum object: dims = [[10], [10]], shape = (10, 10), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

### Operator Example

***Destruction Operator***

The lowering operator, removes elements of a matrix below a particular ground state. It is particularly useful for the case of the Quantum Harmonic Oscillator.

In [79]:
d = destroy(4)

In [80]:
d.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

***Sparse matrices are the default storage type***

In [81]:
d

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

### Matrix Mathematics 

- Adding constants

In [82]:
d + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

adding or subtracting a constant *a* is the equivalent of adding/subtracting $a\hat{I}$ where $\hat{I}$ is the identity matrix.

- Multiplication follows the normal definition of the inner (dot) product

In [83]:
spin_operator = sigmax()

In [84]:
spin_operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [85]:
spin_operator * spin_operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In Bra-Ket notation the inner product is simplified:

$$\langle\psi_{a} | \psi_{b}\rangle$$

Represents the inner product of two vectors, a **bra** on the left and a **ket** on the right.

- Chained dot product

In [86]:
d ** 3

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

Is the equivalent of:

In [87]:
d * d * d

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

### Operations on Quantum Objects

Support exists for a variety of handy linear algebra functions such as eigenvalues, eigenvectors, diagonals, traces, hermitian conjugation etc.

In [88]:
space = basis(8, 1)
space

Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

The adjoint operator $\dagger\$, often referred to as the **dagger** operator takes the transpose of a matrix.

In [89]:
space.dag()

Quantum object: dims = [[1], [8]], shape = (1, 8), type = bra
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0.]]

- Diagonals

In [90]:
coherent_density_matrix = coherent_dm(5,1)
coherent_density_matrix

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [91]:
coherent_density_matrix.diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

- Ladder op example

#### Distance metrics for determining how close to density matrix distributions are to each other

- Trace Distance

- fidelity

- Hilbert-Schmidt distance

- Bures-distance

- Bures angle

- Hellinger distance

***Comparisons of train/test splits for distributions?***

### Quantum Mechanics:

Easy stuff first! 

#### The Time Dependent Schroedinger Equation:

$$i\hbar \frac{\partial \Psi}{\partial t} = -\frac{\hbar^2}{2m}
\frac{\partial^2 \Psi}{\partial x^2} + V \Psi$$

This equation is a PDE, where the wavefunction $\Psi(\hat{r}, t)$ is function of both position and time. 

The Hamiltonian operator $\hat{H}$ represents the classical total energy of a quantum system (Kinetic + Potential).

In operator form:

$$\hat{H}\Psi=E\ \Psi$$

By assuming that the wave function can be expressed as the product of two functions, $\psi(\hat{r})$ and $\phi(t)$, separation of variables can be employed and the separation constant C of the time independent equition represents the allowed energies (eigenenergies) of the operator $\hat{H}$.

It is often favorable to represent the operator $\hat{H}$ in terms of its **eigenvectors** where the resultant matrix consists of all off-diagonal elements equal to zero and the diagonal formed by the eigenenergies.

Let's build a simple neural net from scratch with a relu activation function.

In [92]:
data = np.array([[0,0], [0,1], [1,0], [1,1]])
Qobj(data)

Quantum object: dims = [[4], [2]], shape = (4, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

In [93]:
target = np.array([[0],[1],[1],[1]])
Qobj(target)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [1.]
 [1.]]

In [127]:
start_weights = np.array([[0.2], [0.8]])
Qobj(weights)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.2]
 [0.8]]

In [128]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def activation(x):
    return sigmoid(x)

In [129]:
def sigmoid_prime(x):
    return sigmoid(x)*(1-sigmoid(x))

In [130]:
def activation_prime(x):
    return sigmoid_prime(x)

In [131]:
n_iters = 10000

In [148]:
##
weights = start_weights
bias = 0.5
lr = 0.10
for x in range(n_iters):
    inputs = Qobj(data)
    #print(inputs)
    in_o = inputs * Qobj(weights) + bias
    #print(in_o)
    out_o = Qobj(activation(in_o))
    #print(out_o)
    error = out_o - Qobj(target)
    x = sum(error)
    #print(x)
    
    derror_douto = error
    
    douto_dino = Qobj(activation_prime(out_o))
    
    #print(douto_dino)
    #print(derror_douto)
    deriv = derror_douto 
    for x, d in enumerate(deriv): #does this do a hadamard product/
        deriv.data[x] *= douto_dino.data[x]
    
    #print(deriv)
    
    inputs = inputs.trans()
    #print(inputs)
    deriv_final = inputs * deriv
    #print(deriv_final)
    test = lr * deriv_final
    #print(test)
    weights -= lr * deriv_final
    
    
    for i in deriv:
        #print(i)
        #print(lr * 1)
        bias -= lr * i
    #print(weights.data, end='\r')
    #print(f'bias :{bias}')
    #deriv_final = inputs * deriv

  (0, 0)	(20.414989592637667+0j)
  (0, 0)	(20.41498959265409+0j))
  (0, 0)	(20.414989592670707+0j)
  (0, 0)	(20.414989592687522+0j)
  (0, 0)	(20.414989592704533+0j)
  (0, 0)	(20.414989592721746+0j)
  (0, 0)	(20.41498959273916+0j)
  (0, 0)	(20.414989592756783+0j)
  (0, 0)	(20.414989592774614+0j)
  (0, 0)	(20.414989592792654+0j)
  (0, 0)	(20.414989592810908+0j)
  (0, 0)	(20.41498959282938+0j))
  (0, 0)	(20.414989592848066+0j)
  (0, 0)	(20.414989592866977+0j)
  (0, 0)	(20.414989592886112+0j)
  (0, 0)	(20.41498959290547+0j))
  (0, 0)	(20.41498959292506+0j))
  (0, 0)	(20.41498959294488+0j))
  (0, 0)	(20.414989592964936+0j)
  (0, 0)	(20.414989592985226+0j)
  (0, 0)	(20.414989593005757+0j)
  (0, 0)	(20.41498959302653+0j))
  (0, 0)	(20.414989593047547+0j)
  (0, 0)	(20.414989593068814+0j)
  (0, 0)	(20.414989593090333+0j)
  (0, 0)	(20.414989593112107+0j)
  (0, 0)	(20.414989593134138+0j)
  (0, 0)	(20.414989593156427+0j)
  (0, 0)	(20.41498959317898+0j))
  (0, 0)	(20.414989593201803+0j)
  (0, 0)	(2

  (0, 0)	(20.414989634703275+0j)
  (0, 0)	(20.41498963521689+0j)
  (0, 0)	(20.41498963573658+0j))
  (0, 0)	(20.41498963626241+0j))
  (0, 0)	(20.414989636794452+0j)
  (0, 0)	(20.414989637332784+0j)
  (0, 0)	(20.41498963787748+0j)
  (0, 0)	(20.414989638428615+0j)
  (0, 0)	(20.414989638986263+0j)
  (0, 0)	(20.4149896395505+0j))
  (0, 0)	(20.41498964012141+0j))
  (0, 0)	(20.414989640699066+0j)
  (0, 0)	(20.41498964128355+0j)
  (0, 0)	(20.414989641874943+0j)
  (0, 0)	(20.414989642473326+0j)
  (0, 0)	(20.41498964307878+0j))
  (0, 0)	(20.414989643691392+0j)
  (0, 0)	(20.414989644311245+0j)
  (0, 0)	(20.414989644938423+0j)
  (0, 0)	(20.414989645573016+0j)
  (0, 0)	(20.41498964621511+0j))
  (0, 0)	(20.41498964686479+0j)
  (0, 0)	(20.414989647522148+0j)
  (0, 0)	(20.414989648187277+0j)
  (0, 0)	(20.414989648860267+0j)
  (0, 0)	(20.414989649541212+0j)
  (0, 0)	(20.414989650230204+0j)
  (0, 0)	(20.414989650927343+0j)
  (0, 0)	(20.41498965163272+0j))
  (0, 0)	(20.414989652346435+0j)
  (0, 0)	(20.41

  (0, 0)	(20.414990950282796+0j)
  (0, 0)	(20.414990966345854+0j)
  (0, 0)	(20.41499098259877+0j))
  (0, 0)	(20.414990999043788+0j)
  (0, 0)	(20.414991015683174+0j)
  (0, 0)	(20.41499103251923+0j))
  (0, 0)	(20.414991049554278+0j)
  (0, 0)	(20.41499106679067+0j)
  (0, 0)	(20.41499108423079+0j))
  (0, 0)	(20.41499110187704+0j))
  (0, 0)	(20.414991119731855+0j)
  (0, 0)	(20.414991137797706+0j)
  (0, 0)	(20.414991156077086+0j)
  (0, 0)	(20.414991174572517+0j)
  (0, 0)	(20.414991193286554+0j)
  (0, 0)	(20.41499121222178+0j)
  (0, 0)	(20.414991231380807+0j)
  (0, 0)	(20.414991250766285+0j)
  (0, 0)	(20.414991270380888+0j)
  (0, 0)	(20.414991290227324+0j)
  (0, 0)	(20.414991310308334+0j)
  (0, 0)	(20.41499133062669+0j)
  (0, 0)	(20.414991351185197+0j)
  (0, 0)	(20.414991371986694+0j)
  (0, 0)	(20.414991393034054+0j)
  (0, 0)	(20.41499141433018+0j)
  (0, 0)	(20.414991435878015+0j)
  (0, 0)	(20.414991457680532+0j)
  (0, 0)	(20.414991479740742+0j)
  (0, 0)	(20.414991502061692+0j)
  (0, 0)	(20.4

  (0, 0)	(20.41503209154362+0j))
  (0, 0)	(20.41503259383976+0j)
  (0, 0)	(20.41503310207194+0j))
  (0, 0)	(20.4150336163103+0j))
  (0, 0)	(20.415034136625803+0j)
  (0, 0)	(20.41503466309026+0j)
  (0, 0)	(20.415035195776326+0j)
  (0, 0)	(20.415035734757517+0j)
  (0, 0)	(20.41503628010821+0j))
  (0, 0)	(20.415036831903674+0j)
  (0, 0)	(20.415037390220053+0j)
  (0, 0)	(20.4150379551344+0j))
  (0, 0)	(20.415038526724675+0j)
  (0, 0)	(20.415039105069756+0j)
  (0, 0)	(20.415039690249454+0j)
  (0, 0)	(20.415040282344528+0j)
  (0, 0)	(20.415040881436685+0j)
  (0, 0)	(20.415041487608597+0j)
  (0, 0)	(20.415042100943918+0j)
  (0, 0)	(20.415042721527286+0j)
  (0, 0)	(20.415043349444336+0j)
  (0, 0)	(20.41504398478172+0j)
  (0, 0)	(20.415044627627115+0j)
  (0, 0)	(20.415045278069222+0j)
  (0, 0)	(20.4150459361978+0j)j)
  (0, 0)	(20.415046602103665+0j)
  (0, 0)	(20.41504727587871+0j))
  (0, 0)	(20.415047957615904+0j)
  (0, 0)	(20.41504864740932+0j))
  (0, 0)	(20.415049345354145+0j)
  (0, 0)	(20.41

  (0, 0)	(20.416255181234014+0j)
  (0, 0)	(20.416270108270307+0j)
  (0, 0)	(20.416285210987546+0j)
  (0, 0)	(20.416300491444456+0j)
  (0, 0)	(20.416315951723682+0j)
  (0, 0)	(20.416331593932053+0j)
  (0, 0)	(20.41634742020086+0j))
  (0, 0)	(20.416363432686136+0j)
  (0, 0)	(20.416379633568937+0j)
  (0, 0)	(20.41639602505563+0j))
  (0, 0)	(20.416412609378177+0j)
  (0, 0)	(20.416429388794427+0j)
  (0, 0)	(20.416446365588413+0j)
  (0, 0)	(20.416463542070648+0j)
  (0, 0)	(20.416480920578422+0j)
  (0, 0)	(20.416498503476113+0j)
  (0, 0)	(20.416516293155492+0j)
  (0, 0)	(20.41653429203603+0j))
  (0, 0)	(20.416552502565214+0j)
  (0, 0)	(20.41657092721887+0j))
  (0, 0)	(20.41658956850148+0j)
  (0, 0)	(20.4166084289465+0j)
  (0, 0)	(20.416627511116697+0j)
  (0, 0)	(20.416646817604477+0j)
  (0, 0)	(20.416666351032223+0j)
  (0, 0)	(20.416686114052627+0j)
  (0, 0)	(20.416706109349036+0j)
  (0, 0)	(20.4167263396358+0j)j)
  (0, 0)	(20.416746807658622+0j)
  (0, 0)	(20.41676751619491+0j))
  (0, 0)	(20.

  (0, 0)	(20.447256029978387+0j)
  (0, 0)	(20.44761764767326+0j))
  (0, 0)	(20.44798310322599+0j))
  (0, 0)	(20.44835243272684+0j)
  (0, 0)	(20.44872567250744+0j)
  (0, 0)	(20.449102859140336+0j)
  (0, 0)	(20.449484029438448+0j)
  (0, 0)	(20.44986922045451+0j))
  (0, 0)	(20.45025846948042+0j))
  (0, 0)	(20.45065181404657+0j)
  (0, 0)	(20.45104929192108+0j)
  (0, 0)	(20.45145094110901+0j))
  (0, 0)	(20.451856799851484+0j)
  (0, 0)	(20.452266906624775+0j)
  (0, 0)	(20.452681300139318+0j)
  (0, 0)	(20.45310001933866+0j)
  (0, 0)	(20.453523103398354+0j)
  (0, 0)	(20.45395059172478+0j)
  (0, 0)	(20.454382523953917+0j)
  (0, 0)	(20.45481893995003+0j)
  (0, 0)	(20.4552598798043+0j)j)
  (0, 0)	(20.455705383833383+0j)
  (0, 0)	(20.456155492577913+0j)
  (0, 0)	(20.45661024680092+0j))
  (0, 0)	(20.457069687486182+0j)
  (0, 0)	(20.457533855836502+0j)
  (0, 0)	(20.45800279327193+0j))
  (0, 0)	(20.458476541427896+0j)
  (0, 0)	(20.45895514215326+0j))
  (0, 0)	(20.459438637508324+0j)
  (0, 0)	(20.4599

  (0, 0)	(20.838651717288666+0j)
  (0, 0)	(20.84140497592178+0j))
  (0, 0)	(20.844167037174365+0j)
  (0, 0)	(20.846937859401283+0j)
  (0, 0)	(20.84971740075679+0j)
  (0, 0)	(20.85250561920163+0j))
  (0, 0)	(20.85530247251004+0j)
  (0, 0)	(20.858107918276765+0j)
  (0, 0)	(20.860921913923995+0j)
  (0, 0)	(20.86374441670828+0j))
  (0, 0)	(20.866575383727398+0j)
  (0, 0)	(20.86941477192716+0j))
  (0, 0)	(20.872262538108203+0j)
  (0, 0)	(20.875118638932676+0j)
  (0, 0)	(20.877983030930938+0j)
  (0, 0)	(20.880855670508165+0j)
  (0, 0)	(20.883736513950915+0j)
  (0, 0)	(20.886625517433632+0j)
  (0, 0)	(20.88952263702511+0j))
  (0, 0)	(20.892427828694874+0j)
  (0, 0)	(20.895341048319526+0j)
  (0, 0)	(20.89826225168902+0j)
  (0, 0)	(20.901191394512878+0j)
  (0, 0)	(20.90412843242635+0j))
  (0, 0)	(20.907073320996496+0j)
  (0, 0)	(20.91002601572822+0j)
  (0, 0)	(20.91298647207024+0j))
  (0, 0)	(20.915954645420978+0j)
  (0, 0)	(20.918930491134393+0j)
  (0, 0)	(20.92191396452575+0j)
  (0, 0)	(20.92

  (0, 0)	(21.816382425432117+0j)
  (0, 0)	(21.820214409442237+0j)
  (0, 0)	(21.824047247865547+0j)
  (0, 0)	(21.827880932245886+0j)
  (0, 0)	(21.831715454207593+0j)
  (0, 0)	(21.835550805454805+0j)
  (0, 0)	(21.83938697777076+0j)
  (0, 0)	(21.843223963017117+0j)
  (0, 0)	(21.847061753133243+0j)
  (0, 0)	(21.850900340135553+0j)
  (0, 0)	(21.854739716116825+0j)
  (0, 0)	(21.85857987324552+0j)
  (0, 0)	(21.862420803765133+0j)
  (0, 0)	(21.8662624999935+0j)j)
  (0, 0)	(21.870104954322162+0j)
  (0, 0)	(21.873948159215704+0j)
  (0, 0)	(21.877792107211107+0j)
  (0, 0)	(21.881636790917096+0j)
  (0, 0)	(21.88548220301351+0j))
  (0, 0)	(21.88932833625066+0j))
  (0, 0)	(21.8931751834487+0j))
  (0, 0)	(21.897022737497007+0j)
  (0, 0)	(21.900870991353543+0j)
  (0, 0)	(21.90471993804426+0j))
  (0, 0)	(21.90856957066247+0j)
  (0, 0)	(21.912419882368244+0j)
  (0, 0)	(21.916270866387816+0j)
  (0, 0)	(21.920122516012974+0j)
  (0, 0)	(21.923974824600467+0j)
  (0, 0)	(21.927827785571427+0j)
  (0, 0)	(21.9

  (0, 0)	(22.866087889814317+0j)
  (0, 0)	(22.869999305481223+0j)
  (0, 0)	(22.873910775641335+0j)
  (0, 0)	(22.87782229973635+0j))
  (0, 0)	(22.88173387721368+0j)
  (0, 0)	(22.88564550752638+0j))
  (0, 0)	(22.889557190133097+0j)
  (0, 0)	(22.893468924498013+0j)
  (0, 0)	(22.897380710090786+0j)
  (0, 0)	(22.901292546386504+0j)
  (0, 0)	(22.905204432865617+0j)
  (0, 0)	(22.909116369013883+0j)
  (0, 0)	(22.913028354322332+0j)
  (0, 0)	(22.916940388287184+0j)
  (0, 0)	(22.92085247040982+0j))
  (0, 0)	(22.92476460019672+0j)
  (0, 0)	(22.92867677715941+0j))
  (0, 0)	(22.93258900081441+0j))
  (0, 0)	(22.93650127068319+0j))
  (0, 0)	(22.940413586292113+0j)
  (0, 0)	(22.944325947172384+0j)
  (0, 0)	(22.948238352860006+0j)
  (0, 0)	(22.95215080289573+0j)
  (0, 0)	(22.956063296825004+0j)
  (0, 0)	(22.95997583419793+0j))
  (0, 0)	(22.963888414569208+0j)
  (0, 0)	(22.967801037498095+0j)
  (0, 0)	(22.971713702548357+0j)
  (0, 0)	(22.97562640928823+0j))
  (0, 0)	(22.979539157290358+0j)
  (0, 0)	(22.

  (0, 0)	(23.950533694270472+0j)
  (0, 0)	(23.95445011793395+0j))
  (0, 0)	(23.95836654472781+0j))
  (0, 0)	(23.962282974619917+0j)
  (0, 0)	(23.966199407578458+0j)
  (0, 0)	(23.97011584357195+0j))
  (0, 0)	(23.974032282569233+0j)
  (0, 0)	(23.977948724539466+0j)
  (0, 0)	(23.981865169452124+0j)
  (0, 0)	(23.985781617277+0j)j)
  (0, 0)	(23.98969806798419+0j))
  (0, 0)	(23.9936145215441+0j))
  (0, 0)	(23.997530977927443+0j)
  (0, 0)	(24.00144743710523+0j))
  (0, 0)	(24.00536389904877+0j))
  (0, 0)	(24.009280363729665+0j)
  (0, 0)	(24.01319683111981+0j))
  (0, 0)	(24.017113301191387+0j)
  (0, 0)	(24.021029773916865+0j)
  (0, 0)	(24.024946249268996+0j)
  (0, 0)	(24.02886272722081+0j))
  (0, 0)	(24.03277920774562+0j)
  (0, 0)	(24.036695690817005+0j)
  (0, 0)	(24.040612176408818+0j)
  (0, 0)	(24.04452866449518+0j))
  (0, 0)	(24.04844515505048+0j))
  (0, 0)	(24.052361648049366+0j)
  (0, 0)	(24.056278143466752+0j)
  (0, 0)	(24.060194641277803+0j)
  (0, 0)	(24.064111141457946+0j)
  (0, 0)	(24.

  (0, 0)	(25.043272932165912+0j)
  (0, 0)	(25.04718964358317+0j))
  (0, 0)	(25.051106355176223+0j)
  (0, 0)	(25.055023066943264+0j)
  (0, 0)	(25.058939778882507+0j)
  (0, 0)	(25.062856490992186+0j)
  (0, 0)	(25.066773203270547+0j)
  (0, 0)	(25.07068991571586+0j))
  (0, 0)	(25.07460662832641+0j))
  (0, 0)	(25.078523341100503+0j)
  (0, 0)	(25.082440054036457+0j)
  (0, 0)	(25.08635676713261+0j))
  (0, 0)	(25.090273480387317+0j)
  (0, 0)	(25.09419019379895+0j))
  (0, 0)	(25.098106907365903+0j)
  (0, 0)	(25.102023621086573+0j)
  (0, 0)	(25.105940334959385+0j)
  (0, 0)	(25.10985704898278+0j))
  (0, 0)	(25.113773763155205+0j)
  (0, 0)	(25.117690477475133+0j)
  (0, 0)	(25.12160719194105+0j))
  (0, 0)	(25.125523906551454+0j)
  (0, 0)	(25.129440621304866+0j)
  (0, 0)	(25.133357336199815+0j)
  (0, 0)	(25.137274051234847+0j)
  (0, 0)	(25.141190766408524+0j)
  (0, 0)	(25.14510748171942+0j))
  (0, 0)	(25.14902419716613+0j)
  (0, 0)	(25.152940912747262+0j)
  (0, 0)	(25.156857628461427+0j)
  (0, 0)	(2

  (0, 0)	(26.13995534796551+0j))
  (0, 0)	(26.14387207555103+0j)
  (0, 0)	(26.147788803146298+0j)
  (0, 0)	(26.151705530751233+0j)
  (0, 0)	(26.15562225836574+0j))
  (0, 0)	(26.159538985989716+0j)
  (0, 0)	(26.163455713623065+0j)
  (0, 0)	(26.167372441265695+0j)
  (0, 0)	(26.171289168917504+0j)
  (0, 0)	(26.175205896578404+0j)
  (0, 0)	(26.179122624248297+0j)
  (0, 0)	(26.183039351927093+0j)
  (0, 0)	(26.1869560796147+0j)j)
  (0, 0)	(26.190872807311028+0j)
  (0, 0)	(26.194789535015985+0j)
  (0, 0)	(26.198706262729488+0j)
  (0, 0)	(26.202622990451445+0j)
  (0, 0)	(26.20653971818177+0j)
  (0, 0)	(26.210456445920375+0j)
  (0, 0)	(26.214373173667177+0j)
  (0, 0)	(26.218289901422093+0j)
  (0, 0)	(26.222206629185038+0j)
  (0, 0)	(26.22612335695593+0j)
  (0, 0)	(26.23004008473469+0j)
  (0, 0)	(26.23395681252123+0j)
  (0, 0)	(26.23787354031548+0j))
  (0, 0)	(26.241790268117352+0j)
  (0, 0)	(26.24570699592677+0j))
  (0, 0)	(26.24962372374366+0j)
  (0, 0)	(26.253540451567943+0j)
  (0, 0)	(26.257

  (0, 0)	(27.2797232641311+0j))
  (0, 0)	(27.283639992620692+0j)
  (0, 0)	(27.287556721110768+0j)
  (0, 0)	(27.291473449601323+0j)
  (0, 0)	(27.295390178092354+0j)
  (0, 0)	(27.299306906583855+0j)
  (0, 0)	(27.30322363507582+0j)
  (0, 0)	(27.307140363568244+0j)
  (0, 0)	(27.311057092061123+0j)
  (0, 0)	(27.314973820554453+0j)
  (0, 0)	(27.31889054904823+0j)
  (0, 0)	(27.32280727754245+0j)
  (0, 0)	(27.326724006037104+0j)
  (0, 0)	(27.33064073453219+0j)
  (0, 0)	(27.334557463027704+0j)
  (0, 0)	(27.33847419152364+0j))
  (0, 0)	(27.342390920019998+0j)
  (0, 0)	(27.34630764851677+0j))
  (0, 0)	(27.35022437701395+0j))
  (0, 0)	(27.35414110551154+0j))
  (0, 0)	(27.358057834009532+0j)
  (0, 0)	(27.36197456250792+0j)
  (0, 0)	(27.365891291006704+0j)
  (0, 0)	(27.36980801950588+0j))
  (0, 0)	(27.373724748005436+0j)
  (0, 0)	(27.377641476505378+0j)
  (0, 0)	(27.381558205005696+0j)
  (0, 0)	(27.38547493350639+0j)
  (0, 0)	(27.389391662007455+0j)
  (0, 0)	(27.393308390508885+0j)
  (0, 0)	(27.3972

  (0, 0)	(28.419491263958644+0j)
  (0, 0)	(28.423407992493033+0j)
  (0, 0)	(28.427324721027446+0j)
  (0, 0)	(28.43124144956188+0j))
  (0, 0)	(28.43515817809634+0j))
  (0, 0)	(28.439074906630825+0j)
  (0, 0)	(28.44299163516533+0j)
  (0, 0)	(28.44690836369986+0j))
  (0, 0)	(28.45082509223441+0j))
  (0, 0)	(28.454741820768984+0j)
  (0, 0)	(28.45865854930358+0j))
  (0, 0)	(28.462575277838194+0j)
  (0, 0)	(28.46649200637283+0j))
  (0, 0)	(28.47040873490749+0j))
  (0, 0)	(28.47432546344217+0j)
  (0, 0)	(28.47824219197687+0j)
  (0, 0)	(28.482158920511594+0j)
  (0, 0)	(28.486075649046338+0j)
  (0, 0)	(28.489992377581103+0j)
  (0, 0)	(28.493909106115886+0j)
  (0, 0)	(28.49782583465069+0j)
  (0, 0)	(28.501742563185513+0j)
  (0, 0)	(28.505659291720356+0j)
  (0, 0)	(28.509576020255217+0j)
  (0, 0)	(28.5134927487901+0j)j)
  (0, 0)	(28.517409477325+0j)0j)
  (0, 0)	(28.521326205859918+0j)
  (0, 0)	(28.525242934394853+0j)
  (0, 0)	(28.529159662929807+0j)
  (0, 0)	(28.533076391464782+0j)
  (0, 0)	(28.5

  (0, 0)	(29.555342539389926+0j)
  (0, 0)	(29.559259267926517+0j)
  (0, 0)	(29.56317599646311+0j)
  (0, 0)	(29.5670927249997+0j)j)
  (0, 0)	(29.57100945353629+0j))
  (0, 0)	(29.574926182072886+0j)
  (0, 0)	(29.57884291060948+0j)
  (0, 0)	(29.582759639146076+0j)
  (0, 0)	(29.586676367682674+0j)
  (0, 0)	(29.590593096219273+0j)
  (0, 0)	(29.59450982475587+0j))
  (0, 0)	(29.598426553292473+0j)
  (0, 0)	(29.602343281829075+0j)
  (0, 0)	(29.606260010365677+0j)
  (0, 0)	(29.610176738902283+0j)
  (0, 0)	(29.614093467438888+0j)
  (0, 0)	(29.618010195975494+0j)
  (0, 0)	(29.6219269245121+0j)j)
  (0, 0)	(29.625843653048708+0j)
  (0, 0)	(29.629760381585317+0j)
  (0, 0)	(29.633677110121926+0j)
  (0, 0)	(29.637593838658535+0j)
  (0, 0)	(29.641510567195148+0j)
  (0, 0)	(29.64542729573176+0j))
  (0, 0)	(29.649344024268373+0j)
  (0, 0)	(29.653260752804986+0j)
  (0, 0)	(29.657177481341602+0j)
  (0, 0)	(29.661094209878218+0j)
  (0, 0)	(29.665010938414834+0j)
  (0, 0)	(29.66892766695145+0j))
  (0, 0)	(29

  (0, 0)	(30.695110543559306+0j)
  (0, 0)	(30.699027272095996+0j)
  (0, 0)	(30.70294400063269+0j)
  (0, 0)	(30.706860729169385+0j)
  (0, 0)	(30.71077745770608+0j))
  (0, 0)	(30.714694186242774+0j)
  (0, 0)	(30.718610914779468+0j)
  (0, 0)	(30.722527643316162+0j)
  (0, 0)	(30.726444371852857+0j)
  (0, 0)	(30.73036110038955+0j))
  (0, 0)	(30.734277828926245+0j)
  (0, 0)	(30.73819455746294+0j))
  (0, 0)	(30.742111285999634+0j)
  (0, 0)	(30.74602801453633+0j)
  (0, 0)	(30.749944743073023+0j)
  (0, 0)	(30.753861471609717+0j)
  (0, 0)	(30.75777820014641+0j)
  (0, 0)	(30.761694928683106+0j)
  (0, 0)	(30.7656116572198+0j))
  (0, 0)	(30.769528385756495+0j)
  (0, 0)	(30.77344511429319+0j))
  (0, 0)	(30.777361842829883+0j)
  (0, 0)	(30.781278571366578+0j)
  (0, 0)	(30.785195299903272+0j)
  (0, 0)	(30.789112028439966+0j)
  (0, 0)	(30.79302875697666+0j))
  (0, 0)	(30.796945485513355+0j)
  (0, 0)	(30.80086221405005+0j))
  (0, 0)	(30.804778942586744+0j)
  (0, 0)	(30.808695671123438+0j)
  (0, 0)	(30.8

  (0, 0)	(31.82312836212727+0j))
  (0, 0)	(31.827045090663965+0j)
  (0, 0)	(31.83096181920066+0j)
  (0, 0)	(31.834878547737354+0j)
  (0, 0)	(31.83879527627405+0j)
  (0, 0)	(31.842712004810743+0j)
  (0, 0)	(31.846628733347437+0j)
  (0, 0)	(31.85054546188413+0j))
  (0, 0)	(31.854462190420826+0j)
  (0, 0)	(31.85837891895752+0j))
  (0, 0)	(31.862295647494214+0j)
  (0, 0)	(31.86621237603091+0j))
  (0, 0)	(31.870129104567603+0j)
  (0, 0)	(31.874045833104297+0j)
  (0, 0)	(31.87796256164099+0j))
  (0, 0)	(31.881879290177686+0j)
  (0, 0)	(31.88579601871438+0j)
  (0, 0)	(31.889712747251075+0j)
  (0, 0)	(31.89362947578777+0j)
  (0, 0)	(31.897546204324463+0j)
  (0, 0)	(31.901462932861158+0j)
  (0, 0)	(31.905379661397852+0j)
  (0, 0)	(31.909296389934546+0j)
  (0, 0)	(31.91321311847124+0j))
  (0, 0)	(31.917129847007935+0j)
  (0, 0)	(31.92104657554463+0j))
  (0, 0)	(31.924963304081324+0j)
  (0, 0)	(31.928880032618018+0j)
  (0, 0)	(31.932796761154712+0j)
  (0, 0)	(31.936713489691407+0j)
  (0, 0)	(31.9

  (0, 0)	(32.96289636630532+0j))
  (0, 0)	(32.96681309484202+0j)
  (0, 0)	(32.97072982337871+0j))
  (0, 0)	(32.974646551915406+0j)
  (0, 0)	(32.9785632804521+0j))
  (0, 0)	(32.982480008988794+0j)
  (0, 0)	(32.98639673752549+0j)
  (0, 0)	(32.99031346606218+0j))
  (0, 0)	(32.99423019459888+0j)
  (0, 0)	(32.99814692313557+0j))
  (0, 0)	(33.002063651672266+0j)
  (0, 0)	(33.00598038020896+0j)
  (0, 0)	(33.009897108745655+0j)
  (0, 0)	(33.01381383728235+0j)
  (0, 0)	(33.01773056581904+0j))
  (0, 0)	(33.02164729435574+0j)
  (0, 0)	(33.02556402289243+0j))
  (0, 0)	(33.029480751429126+0j)
  (0, 0)	(33.03339747996582+0j))
  (0, 0)	(33.037314208502515+0j)
  (0, 0)	(33.04123093703921+0j)
  (0, 0)	(33.045147665575904+0j)
  (0, 0)	(33.0490643941126+0j))
  (0, 0)	(33.05298112264929+0j))
  (0, 0)	(33.05689785118599+0j)
  (0, 0)	(33.06081457972268+0j))
  (0, 0)	(33.064731308259375+0j)
  (0, 0)	(33.06864803679607+0j)
  (0, 0)	(33.072564765332764+0j)
  (0, 0)	(33.07648149386946+0j)
  (0, 0)	(33.080398222

  (0, 0)	(34.102664370483375+0j)
  (0, 0)	(34.10658109902007+0j)
  (0, 0)	(34.11049782755676+0j))
  (0, 0)	(34.11441455609346+0j)
  (0, 0)	(34.11833128463015+0j))
  (0, 0)	(34.122248013166846+0j)
  (0, 0)	(34.12616474170354+0j)
  (0, 0)	(34.130081470240235+0j)
  (0, 0)	(34.13399819877693+0j)
  (0, 0)	(34.13791492731362+0j))
  (0, 0)	(34.14183165585032+0j)
  (0, 0)	(34.14574838438701+0j))
  (0, 0)	(34.14966511292371+0j)
  (0, 0)	(34.1535818414604+0j)j)
  (0, 0)	(34.157498569997095+0j)
  (0, 0)	(34.16141529853379+0j)
  (0, 0)	(34.165332027070484+0j)
  (0, 0)	(34.16924875560718+0j)
  (0, 0)	(34.17316548414387+0j))
  (0, 0)	(34.17708221268057+0j)
  (0, 0)	(34.18099894121726+0j))
  (0, 0)	(34.184915669753956+0j)
  (0, 0)	(34.18883239829065+0j)
  (0, 0)	(34.192749126827344+0j)
  (0, 0)	(34.19666585536404+0j)
  (0, 0)	(34.20058258390073+0j))
  (0, 0)	(34.20449931243743+0j)
  (0, 0)	(34.20841604097412+0j))
  (0, 0)	(34.212332769510816+0j)
  (0, 0)	(34.21624949804751+0j)
  (0, 0)	(34.2201662265

  (0, 0)	(35.23851564612473+0j))
  (0, 0)	(35.242432374661426+0j)
  (0, 0)	(35.24634910319812+0j)
  (0, 0)	(35.250265831734815+0j)
  (0, 0)	(35.25418256027151+0j)
  (0, 0)	(35.258099288808204+0j)
  (0, 0)	(35.2620160173449+0j))
  (0, 0)	(35.26593274588159+0j))
  (0, 0)	(35.26984947441829+0j)
  (0, 0)	(35.27376620295498+0j))
  (0, 0)	(35.277682931491675+0j)
  (0, 0)	(35.28159966002837+0j)
  (0, 0)	(35.285516388565064+0j)
  (0, 0)	(35.28943311710176+0j)
  (0, 0)	(35.29334984563845+0j))
  (0, 0)	(35.29726657417515+0j)
  (0, 0)	(35.30118330271184+0j))
  (0, 0)	(35.305100031248536+0j)
  (0, 0)	(35.30901675978523+0j)
  (0, 0)	(35.312933488321924+0j)
  (0, 0)	(35.31685021685862+0j)
  (0, 0)	(35.32076694539531+0j))
  (0, 0)	(35.32468367393201+0j)
  (0, 0)	(35.3286004024687+0j)j)
  (0, 0)	(35.332517131005396+0j)
  (0, 0)	(35.33643385954209+0j)
  (0, 0)	(35.340350588078785+0j)
  (0, 0)	(35.34426731661548+0j)
  (0, 0)	(35.34818404515217+0j))
  (0, 0)	(35.35210077368887+0j)
  (0, 0)	(35.3560175022

  (0, 0)	(36.370450193229395+0j)
  (0, 0)	(36.37436692176609+0j)
  (0, 0)	(36.378283650302784+0j)
  (0, 0)	(36.38220037883948+0j)
  (0, 0)	(36.38611710737617+0j))
  (0, 0)	(36.39003383591287+0j)
  (0, 0)	(36.39395056444956+0j))
  (0, 0)	(36.397867292986255+0j)
  (0, 0)	(36.40178402152295+0j)
  (0, 0)	(36.405700750059644+0j)
  (0, 0)	(36.40961747859634+0j)
  (0, 0)	(36.41353420713303+0j))
  (0, 0)	(36.41745093566973+0j)
  (0, 0)	(36.42136766420642+0j))
  (0, 0)	(36.425284392743116+0j)
  (0, 0)	(36.42920112127981+0j)
  (0, 0)	(36.433117849816504+0j)
  (0, 0)	(36.4370345783532+0j))
  (0, 0)	(36.44095130688989+0j))
  (0, 0)	(36.44486803542659+0j)
  (0, 0)	(36.44878476396328+0j))
  (0, 0)	(36.452701492499976+0j)
  (0, 0)	(36.45661822103667+0j)
  (0, 0)	(36.460534949573365+0j)
  (0, 0)	(36.46445167811006+0j)
  (0, 0)	(36.46836840664675+0j))
  (0, 0)	(36.47228513518345+0j)
  (0, 0)	(36.47620186372014+0j))
  (0, 0)	(36.48011859225684+0j)
  (0, 0)	(36.48403532079353+0j))
  (0, 0)	(36.4879520493

  (0, 0)	(37.51021819740745+0j)
  (0, 0)	(37.51413492594414+0j))
  (0, 0)	(37.518051654480836+0j)
  (0, 0)	(37.52196838301753+0j)
  (0, 0)	(37.525885111554224+0j)
  (0, 0)	(37.52980184009092+0j)
  (0, 0)	(37.53371856862761+0j))
  (0, 0)	(37.53763529716431+0j)
  (0, 0)	(37.541552025701+0j)0j)
  (0, 0)	(37.545468754237696+0j)
  (0, 0)	(37.54938548277439+0j)
  (0, 0)	(37.553302211311085+0j)
  (0, 0)	(37.55721893984778+0j)
  (0, 0)	(37.56113566838447+0j))
  (0, 0)	(37.56505239692117+0j)
  (0, 0)	(37.56896912545786+0j))
  (0, 0)	(37.572885853994556+0j)
  (0, 0)	(37.57680258253125+0j)
  (0, 0)	(37.580719311067945+0j)
  (0, 0)	(37.58463603960464+0j)
  (0, 0)	(37.588552768141334+0j)
  (0, 0)	(37.59246949667803+0j)
  (0, 0)	(37.59638622521472+0j))
  (0, 0)	(37.60030295375142+0j)
  (0, 0)	(37.60421968228811+0j))
  (0, 0)	(37.608136410824805+0j)
  (0, 0)	(37.6120531393615+0j))
  (0, 0)	(37.615969867898194+0j)
  (0, 0)	(37.61988659643489+0j)
  (0, 0)	(37.62380332497158+0j))
  (0, 0)	(37.6277200535

  (0, 0)	(38.6499862015855+0j))
  (0, 0)	(38.65390293012219+0j))
  (0, 0)	(38.65781965865889+0j)
  (0, 0)	(38.66173638719558+0j))
  (0, 0)	(38.665653115732276+0j)
  (0, 0)	(38.66956984426897+0j)
  (0, 0)	(38.673486572805665+0j)
  (0, 0)	(38.67740330134236+0j)
  (0, 0)	(38.68132002987905+0j))
  (0, 0)	(38.68523675841575+0j)
  (0, 0)	(38.68915348695244+0j))
  (0, 0)	(38.693070215489136+0j)
  (0, 0)	(38.69698694402583+0j)
  (0, 0)	(38.700903672562525+0j)
  (0, 0)	(38.70482040109922+0j)
  (0, 0)	(38.708737129635914+0j)
  (0, 0)	(38.71265385817261+0j)
  (0, 0)	(38.7165705867093+0j)j)
  (0, 0)	(38.720487315246+0j)j)
  (0, 0)	(38.72440404378269+0j))
  (0, 0)	(38.728320772319385+0j)
  (0, 0)	(38.73223750085608+0j)
  (0, 0)	(38.736154229392774+0j)
  (0, 0)	(38.74007095792947+0j)
  (0, 0)	(38.74398768646616+0j))
  (0, 0)	(38.74790441500286+0j)
  (0, 0)	(38.75182114353955+0j))
  (0, 0)	(38.755737872076246+0j)
  (0, 0)	(38.75965460061294+0j)
  (0, 0)	(38.763571329149634+0j)
  (0, 0)	(38.7674880576

  (0, 0)	(39.79758766283694+0j)
  (0, 0)	(39.80150439137363+0j))
  (0, 0)	(39.80542111991033+0j)
  (0, 0)	(39.80933784844702+0j))
  (0, 0)	(39.81325457698372+0j)
  (0, 0)	(39.81717130552041+0j))
  (0, 0)	(39.821088034057105+0j)
  (0, 0)	(39.8250047625938+0j))
  (0, 0)	(39.828921491130494+0j)
  (0, 0)	(39.83283821966719+0j)
  (0, 0)	(39.83675494820388+0j))
  (0, 0)	(39.84067167674058+0j)
  (0, 0)	(39.84458840527727+0j))
  (0, 0)	(39.848505133813966+0j)
  (0, 0)	(39.85242186235066+0j)
  (0, 0)	(39.856338590887354+0j)
  (0, 0)	(39.86025531942405+0j)
  (0, 0)	(39.86417204796074+0j))
  (0, 0)	(39.86808877649744+0j)
  (0, 0)	(39.87200550503413+0j))
  (0, 0)	(39.875922233570826+0j)
  (0, 0)	(39.87983896210752+0j)
  (0, 0)	(39.883755690644215+0j)
  (0, 0)	(39.88767241918091+0j)
  (0, 0)	(39.8915891477176+0j)j)
  (0, 0)	(39.8955058762543+0j))
  (0, 0)	(39.89942260479099+0j))
  (0, 0)	(39.903339333327686+0j)
  (0, 0)	(39.90725606186438+0j)
  (0, 0)	(39.911172790401075+0j)
  (0, 0)	(39.9150895189

  (0, 0)	(40.9334389384783+0j))
  (0, 0)	(40.93735566701499+0j))
  (0, 0)	(40.941272395551685+0j)
  (0, 0)	(40.94518912408838+0j)
  (0, 0)	(40.949105852625074+0j)
  (0, 0)	(40.95302258116177+0j)
  (0, 0)	(40.95693930969846+0j))
  (0, 0)	(40.96085603823516+0j)
  (0, 0)	(40.96477276677185+0j))
  (0, 0)	(40.968689495308546+0j)
  (0, 0)	(40.97260622384524+0j)
  (0, 0)	(40.976522952381934+0j)
  (0, 0)	(40.98043968091863+0j)
  (0, 0)	(40.98435640945532+0j))
  (0, 0)	(40.98827313799202+0j)
  (0, 0)	(40.99218986652871+0j))
  (0, 0)	(40.996106595065406+0j)
  (0, 0)	(41.0000233236021+0j))
  (0, 0)	(41.003940052138795+0j)
  (0, 0)	(41.00785678067549+0j)
  (0, 0)	(41.01177350921218+0j))
  (0, 0)	(41.01569023774888+0j)
  (0, 0)	(41.01960696628557+0j))
  (0, 0)	(41.023523694822266+0j)
  (0, 0)	(41.02744042335896+0j)
  (0, 0)	(41.031357151895655+0j)
  (0, 0)	(41.03527388043235+0j)
  (0, 0)	(41.039190608969044+0j)
  (0, 0)	(41.04310733750574+0j)
  (0, 0)	(41.04702406604243+0j))
  (0, 0)	(41.0509407945

  (0, 0)	(42.07320694265635+0j)
  (0, 0)	(42.07712367119304+0j))
  (0, 0)	(42.08104039972974+0j)
  (0, 0)	(42.08495712826643+0j))
  (0, 0)	(42.088873856803126+0j)
  (0, 0)	(42.09279058533982+0j)
  (0, 0)	(42.096707313876514+0j)
  (0, 0)	(42.10062404241321+0j)
  (0, 0)	(42.1045407709499+0j)j)
  (0, 0)	(42.1084574994866+0j))
  (0, 0)	(42.11237422802329+0j))
  (0, 0)	(42.116290956559986+0j)
  (0, 0)	(42.12020768509668+0j)
  (0, 0)	(42.124124413633375+0j)
  (0, 0)	(42.12804114217007+0j)
  (0, 0)	(42.13195787070676+0j))
  (0, 0)	(42.13587459924346+0j)
  (0, 0)	(42.13979132778015+0j))
  (0, 0)	(42.14370805631685+0j)
  (0, 0)	(42.14762478485354+0j))
  (0, 0)	(42.151541513390235+0j)
  (0, 0)	(42.15545824192693+0j)
  (0, 0)	(42.159374970463624+0j)
  (0, 0)	(42.16329169900032+0j)
  (0, 0)	(42.16720842753701+0j))
  (0, 0)	(42.17112515607371+0j)
  (0, 0)	(42.1750418846104+0j)j)
  (0, 0)	(42.178958613147095+0j)
  (0, 0)	(42.18287534168379+0j)
  (0, 0)	(42.186792070220484+0j)
  (0, 0)	(42.1907087987

  (0, 0)	(43.2129749468344+0j))
  (0, 0)	(43.216891675371095+0j)
  (0, 0)	(43.22080840390779+0j)
  (0, 0)	(43.22472513244448+0j))
  (0, 0)	(43.22864186098118+0j)
  (0, 0)	(43.23255858951787+0j))
  (0, 0)	(43.236475318054566+0j)
  (0, 0)	(43.24039204659126+0j)
  (0, 0)	(43.244308775127955+0j)
  (0, 0)	(43.24822550366465+0j)
  (0, 0)	(43.252142232201344+0j)
  (0, 0)	(43.25605896073804+0j)
  (0, 0)	(43.25997568927473+0j))
  (0, 0)	(43.26389241781143+0j)
  (0, 0)	(43.26780914634812+0j))
  (0, 0)	(43.271725874884815+0j)
  (0, 0)	(43.27564260342151+0j)
  (0, 0)	(43.279559331958204+0j)
  (0, 0)	(43.2834760604949+0j))
  (0, 0)	(43.28739278903159+0j))
  (0, 0)	(43.29130951756829+0j)
  (0, 0)	(43.29522624610498+0j))
  (0, 0)	(43.299142974641676+0j)
  (0, 0)	(43.30305970317837+0j)
  (0, 0)	(43.306976431715064+0j)
  (0, 0)	(43.31089316025176+0j)
  (0, 0)	(43.31480988878845+0j))
  (0, 0)	(43.31872661732515+0j)
  (0, 0)	(43.32264334586184+0j))
  (0, 0)	(43.326560074398536+0j)
  (0, 0)	(43.3304768029

  (0, 0)	(44.356659679549146+0j)
  (0, 0)	(44.36057640808584+0j)
  (0, 0)	(44.364493136622535+0j)
  (0, 0)	(44.36840986515923+0j)
  (0, 0)	(44.372326593695924+0j)
  (0, 0)	(44.37624332223262+0j)
  (0, 0)	(44.38016005076931+0j))
  (0, 0)	(44.38407677930601+0j)
  (0, 0)	(44.3879935078427+0j)j)
  (0, 0)	(44.391910236379395+0j)
  (0, 0)	(44.39582696491609+0j)
  (0, 0)	(44.399743693452784+0j)
  (0, 0)	(44.40366042198948+0j)
  (0, 0)	(44.40757715052617+0j))
  (0, 0)	(44.41149387906287+0j)
  (0, 0)	(44.41541060759956+0j))
  (0, 0)	(44.419327336136256+0j)
  (0, 0)	(44.42324406467295+0j)
  (0, 0)	(44.427160793209644+0j)
  (0, 0)	(44.43107752174634+0j)
  (0, 0)	(44.43499425028303+0j))
  (0, 0)	(44.43891097881973+0j)
  (0, 0)	(44.44282770735642+0j))
  (0, 0)	(44.446744435893116+0j)
  (0, 0)	(44.45066116442981+0j)
  (0, 0)	(44.454577892966505+0j)
  (0, 0)	(44.4584946215032+0j))
  (0, 0)	(44.46241135003989+0j))
  (0, 0)	(44.46632807857659+0j)
  (0, 0)	(44.47024480711328+0j))
  (0, 0)	(44.4741615356

  (0, 0)	(45.492510955190504+0j)
  (0, 0)	(45.4964276837272+0j))
  (0, 0)	(45.50034441226389+0j))
  (0, 0)	(45.50426114080059+0j)
  (0, 0)	(45.50817786933728+0j))
  (0, 0)	(45.512094597873975+0j)
  (0, 0)	(45.51601132641067+0j)
  (0, 0)	(45.519928054947364+0j)
  (0, 0)	(45.52384478348406+0j)
  (0, 0)	(45.52776151202075+0j))
  (0, 0)	(45.53167824055745+0j)
  (0, 0)	(45.53559496909414+0j))
  (0, 0)	(45.539511697630836+0j)
  (0, 0)	(45.54342842616753+0j)
  (0, 0)	(45.547345154704225+0j)
  (0, 0)	(45.55126188324092+0j)
  (0, 0)	(45.55517861177761+0j))
  (0, 0)	(45.55909534031431+0j)
  (0, 0)	(45.563012068851+0j)0j)
  (0, 0)	(45.566928797387696+0j)
  (0, 0)	(45.57084552592439+0j)
  (0, 0)	(45.574762254461085+0j)
  (0, 0)	(45.57867898299778+0j)
  (0, 0)	(45.58259571153447+0j))
  (0, 0)	(45.58651244007117+0j)
  (0, 0)	(45.59042916860786+0j))
  (0, 0)	(45.59434589714456+0j)
  (0, 0)	(45.59826262568125+0j))
  (0, 0)	(45.602179354217945+0j)
  (0, 0)	(45.60609608275464+0j)
  (0, 0)	(45.6100128112

  (0, 0)	(46.640112416441944+0j)
  (0, 0)	(46.64402914497864+0j)
  (0, 0)	(46.64794587351533+0j))
  (0, 0)	(46.65186260205203+0j)
  (0, 0)	(46.65577933058872+0j))
  (0, 0)	(46.659696059125416+0j)
  (0, 0)	(46.66361278766211+0j)
  (0, 0)	(46.667529516198805+0j)
  (0, 0)	(46.6714462447355+0j))
  (0, 0)	(46.67536297327219+0j))
  (0, 0)	(46.67927970180889+0j)
  (0, 0)	(46.68319643034558+0j))
  (0, 0)	(46.687113158882276+0j)
  (0, 0)	(46.69102988741897+0j)
  (0, 0)	(46.694946615955665+0j)
  (0, 0)	(46.69886334449236+0j)
  (0, 0)	(46.702780073029054+0j)
  (0, 0)	(46.70669680156575+0j)
  (0, 0)	(46.71061353010244+0j))
  (0, 0)	(46.71453025863914+0j)
  (0, 0)	(46.71844698717583+0j))
  (0, 0)	(46.722363715712525+0j)
  (0, 0)	(46.72628044424922+0j)
  (0, 0)	(46.730197172785914+0j)
  (0, 0)	(46.73411390132261+0j)
  (0, 0)	(46.7380306298593+0j)j)
  (0, 0)	(46.741947358396+0j)j)
  (0, 0)	(46.74586408693269+0j))
  (0, 0)	(46.749780815469386+0j)
  (0, 0)	(46.75369754400608+0j)
  (0, 0)	(46.7576142725

  (0, 0)	(47.76813023500991+0j))
  (0, 0)	(47.77204696354661+0j)
  (0, 0)	(47.7759636920833+0j)j)
  (0, 0)	(47.779880420619996+0j)
  (0, 0)	(47.78379714915669+0j)
  (0, 0)	(47.787713877693385+0j)
  (0, 0)	(47.79163060623008+0j)
  (0, 0)	(47.79554733476677+0j))
  (0, 0)	(47.79946406330347+0j)
  (0, 0)	(47.80338079184016+0j))
  (0, 0)	(47.807297520376856+0j)
  (0, 0)	(47.81121424891355+0j))
  (0, 0)	(47.815130977450245+0j)
  (0, 0)	(47.81904770598694+0j)
  (0, 0)	(47.822964434523634+0j)
  (0, 0)	(47.82688116306033+0j)
  (0, 0)	(47.83079789159702+0j))
  (0, 0)	(47.83471462013372+0j)
  (0, 0)	(47.83863134867041+0j))
  (0, 0)	(47.842548077207105+0j)
  (0, 0)	(47.8464648057438+0j))
  (0, 0)	(47.850381534280494+0j)
  (0, 0)	(47.85429826281719+0j)
  (0, 0)	(47.85821499135388+0j))
  (0, 0)	(47.86213171989058+0j)
  (0, 0)	(47.86604844842727+0j))
  (0, 0)	(47.869965176963966+0j)
  (0, 0)	(47.87388190550066+0j)
  (0, 0)	(47.877798634037354+0j)
  (0, 0)	(47.88171536257405+0j)
  (0, 0)	(47.885632091

  (0, 0)	(48.90398151065127+0j)
  (0, 0)	(48.907898239187965+0j)
  (0, 0)	(48.91181496772466+0j)
  (0, 0)	(48.91573169626135+0j))
  (0, 0)	(48.91964842479805+0j)
  (0, 0)	(48.92356515333474+0j))
  (0, 0)	(48.92748188187144+0j)
  (0, 0)	(48.93139861040813+0j))
  (0, 0)	(48.935315338944825+0j)
  (0, 0)	(48.93923206748152+0j)
  (0, 0)	(48.943148796018214+0j)
  (0, 0)	(48.94706552455491+0j)
  (0, 0)	(48.9509822530916+0j)j)
  (0, 0)	(48.9548989816283+0j))
  (0, 0)	(48.95881571016499+0j))
  (0, 0)	(48.962732438701686+0j)
  (0, 0)	(48.96664916723838+0j)
  (0, 0)	(48.970565895775074+0j)
  (0, 0)	(48.97448262431177+0j)
  (0, 0)	(48.97839935284846+0j))
  (0, 0)	(48.98231608138516+0j)
  (0, 0)	(48.98623280992185+0j))
  (0, 0)	(48.990149538458546+0j)
  (0, 0)	(48.99406626699524+0j)
  (0, 0)	(48.997982995531935+0j)
  (0, 0)	(49.00189972406863+0j)
  (0, 0)	(49.00581645260532+0j))
  (0, 0)	(49.00973318114202+0j)
  (0, 0)	(49.01364990967871+0j))
  (0, 0)	(49.017566638215406+0j)
  (0, 0)	(49.0214833667

  (0, 0)	(50.03983278629263+0j)
  (0, 0)	(50.04374951482932+0j))
  (0, 0)	(50.04766624336602+0j)
  (0, 0)	(50.05158297190271+0j))
  (0, 0)	(50.055499700439405+0j)
  (0, 0)	(50.0594164289761+0j))
  (0, 0)	(50.063333157512794+0j)
  (0, 0)	(50.06724988604949+0j)
  (0, 0)	(50.07116661458618+0j))
  (0, 0)	(50.07508334312288+0j)
  (0, 0)	(50.07900007165957+0j))
  (0, 0)	(50.082916800196266+0j)
  (0, 0)	(50.08683352873296+0j)
  (0, 0)	(50.090750257269654+0j)
  (0, 0)	(50.09466698580635+0j)
  (0, 0)	(50.09858371434304+0j))
  (0, 0)	(50.10250044287974+0j)
  (0, 0)	(50.10641717141643+0j))
  (0, 0)	(50.110333899953126+0j)
  (0, 0)	(50.11425062848982+0j)
  (0, 0)	(50.118167357026515+0j)
  (0, 0)	(50.12208408556321+0j)
  (0, 0)	(50.1260008140999+0j)j)
  (0, 0)	(50.1299175426366+0j))
  (0, 0)	(50.13383427117329+0j))
  (0, 0)	(50.137750999709986+0j)
  (0, 0)	(50.14166772824668+0j)
  (0, 0)	(50.145584456783375+0j)
  (0, 0)	(50.14950118532007+0j)
  (0, 0)	(50.153417913856764+0j)
  (0, 0)	(50.1573346423

  (0, 0)	(51.17960079047068+0j)
  (0, 0)	(51.183517519007374+0j)
  (0, 0)	(51.18743424754407+0j)
  (0, 0)	(51.19135097608076+0j))
  (0, 0)	(51.19526770461746+0j)
  (0, 0)	(51.19918443315415+0j))
  (0, 0)	(51.203101161690846+0j)
  (0, 0)	(51.20701789022754+0j)
  (0, 0)	(51.210934618764234+0j)
  (0, 0)	(51.21485134730093+0j)
  (0, 0)	(51.21876807583762+0j))
  (0, 0)	(51.22268480437432+0j)
  (0, 0)	(51.22660153291101+0j))
  (0, 0)	(51.230518261447706+0j)
  (0, 0)	(51.2344349899844+0j))
  (0, 0)	(51.238351718521095+0j)
  (0, 0)	(51.24226844705779+0j)
  (0, 0)	(51.24618517559448+0j))
  (0, 0)	(51.25010190413118+0j)
  (0, 0)	(51.25401863266787+0j))
  (0, 0)	(51.25793536120457+0j)
  (0, 0)	(51.26185208974126+0j))
  (0, 0)	(51.265768818277955+0j)
  (0, 0)	(51.26968554681465+0j)
  (0, 0)	(51.273602275351344+0j)
  (0, 0)	(51.27751900388804+0j)
  (0, 0)	(51.28143573242473+0j))
  (0, 0)	(51.28535246096143+0j)
  (0, 0)	(51.28926918949812+0j))
  (0, 0)	(51.293185918034816+0j)
  (0, 0)	(51.2971026465

  (0, 0)	(52.31936879464873+0j))
  (0, 0)	(52.323285523185426+0j)
  (0, 0)	(52.32720225172212+0j)
  (0, 0)	(52.331118980258815+0j)
  (0, 0)	(52.33503570879551+0j)
  (0, 0)	(52.3389524373322+0j)j)
  (0, 0)	(52.3428691658689+0j))
  (0, 0)	(52.34678589440559+0j))
  (0, 0)	(52.350702622942286+0j)
  (0, 0)	(52.35461935147898+0j)
  (0, 0)	(52.358536080015675+0j)
  (0, 0)	(52.36245280855237+0j)
  (0, 0)	(52.366369537089064+0j)
  (0, 0)	(52.37028626562576+0j)
  (0, 0)	(52.37420299416245+0j))
  (0, 0)	(52.37811972269915+0j)
  (0, 0)	(52.38203645123584+0j))
  (0, 0)	(52.385953179772535+0j)
  (0, 0)	(52.38986990830923+0j)
  (0, 0)	(52.393786636845924+0j)
  (0, 0)	(52.39770336538262+0j)
  (0, 0)	(52.40162009391931+0j))
  (0, 0)	(52.40553682245601+0j)
  (0, 0)	(52.4094535509927+0j)j)
  (0, 0)	(52.413370279529396+0j)
  (0, 0)	(52.41728700806609+0j)
  (0, 0)	(52.421203736602784+0j)
  (0, 0)	(52.42512046513948+0j)
  (0, 0)	(52.42903719367617+0j))
  (0, 0)	(52.43295392221287+0j)
  (0, 0)	(52.4368706507

In [133]:
bias

array([[-18.92693122+0.j]])

In [134]:
print(weights.data)

  (0, 0)	(20.414989592621435+0j)
  (1, 0)	(20.41498961783083+0j)


Make predictions:

In [135]:
inputs = Qobj(np.array([1,1]))

In [136]:
inputs.trans()

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 1.]]

In [137]:
result = inputs.trans() * weights + bias

In [138]:
activation(result)

array([[1.+0.j]])

In [139]:
inputs = Qobj(np.array([0,0]))

In [140]:
result = inputs.trans() * weights + bias

In [141]:
activation(result)

array([[6.02751371e-09+0.j]])

In [142]:
inputs = Qobj(np.array([0,1]))

In [143]:
result = inputs.trans() * weights + bias

In [144]:
activation(result)

array([[0.81578667+0.j]])

In [145]:
inputs = Qobj(np.array([1,0]))

In [146]:
result = inputs.trans() * weights + bias

In [147]:
activation(result)

array([[0.81578667+0.j]])