In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### The Quantum Object 


### Bra-Ket Notation

In [2]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

The base quantum object is a **bra** vector denoted by $\langle \psi|$

This is the equivalent of a 1x1 matrix with zero as the only entry.

Creating a bra vector with data using list comp:

In [3]:
Qobj([[x for x in range(5)]])

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[0. 1. 2. 3. 4.]]

In [4]:
Qobj([[x] for x in range(5)])

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]]

A **ket** vector, represented by $|\psi\rangle$ is the equivalent of a column vector. In this notation, we have created a 1x5 column vector.

- qtip rundown

- Bra / Ket notation

- Commutators

- Spin

- tunneling

- Hilbert Space

- Back prop parameters


A random vector, really an **operator**

In [5]:
r = np.random.rand(4,4)
r

array([[0.29698365, 0.37517332, 0.88386324, 0.21341024],
       [0.30875471, 0.51132932, 0.13289657, 0.29161619],
       [0.48807335, 0.08931133, 0.13178977, 0.57406734],
       [0.47620442, 0.07381817, 0.21138972, 0.45439588]])

In [6]:
Qobj(r)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.29698365 0.37517332 0.88386324 0.21341024]
 [0.30875471 0.51132932 0.13289657 0.29161619]
 [0.48807335 0.08931133 0.13178977 0.57406734]
 [0.47620442 0.07381817 0.21138972 0.45439588]]

### Creating a Hilbert Space

### fock state operator

- The equivalent of a particle selector operator $\hat{N}_{k}$ where $\sum_{i}\hat{N}_{k_{i}}$ = $\hat{N}$ (the total number of particles in a system).

In [7]:
basis(10, 3)

Quantum object: dims = [[10], [1]], shape = (10, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In multi-dimensional space:

In [8]:
fock_dm(10, 3)

Quantum object: dims = [[10], [10]], shape = (10, 10), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

### Operator Example

***Destruction Operator***

The lowering operator, removes elements of a matrix below a particular ground state. It is particularly useful for the case of the Quantum Harmonic Oscillator.

In [9]:
d = destroy(4)

In [10]:
d.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

***Sparse matrices are the default storage type***

In [11]:
d

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

### Matrix Mathematics 

- Adding constants

In [12]:
d + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

adding or subtracting a constant *a* is the equivalent of adding/subtracting $a\hat{I}$ where $\hat{I}$ is the identity matrix.

- Multiplication follows the normal definition of the inner (dot) product

In [13]:
spin_operator = sigmax()

In [14]:
spin_operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [15]:
spin_operator * spin_operator

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In Bra-Ket notation the inner product is simplified:

$$\langle\psi_{a} | \psi_{b}\rangle$$

Represents the inner product of two vectors, a **bra** on the left and a **ket** on the right.

- Chained dot product

In [16]:
d ** 3

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

Is the equivalent of:

In [17]:
d * d * d

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

### Operations on Quantum Objects

Support exists for a variety of handy linear algebra functions such as eigenvalues, eigenvectors, diagonals, traces, hermitian conjugation etc.

In [18]:
space = basis(8, 1)
space

Quantum object: dims = [[8], [1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

The adjoint operator $\dagger\$, often referred to as the **dagger** operator takes the transpose of a matrix.

In [19]:
space.dag()

Quantum object: dims = [[1], [8]], shape = (1, 8), type = bra
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0.]]

- Diagonals

In [20]:
coherent_density_matrix = coherent_dm(5,1)
coherent_density_matrix

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [21]:
coherent_density_matrix.diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

- Ladder op example

#### Distance metrics for determining how close to density matrix distributions are to each other

- Trace Distance

- fidelity

- Hilbert-Schmidt distance

- Bures-distance

- Bures angle

- Hellinger distance

***Comparisons of train/test splits for distributions?***

### Quantum Mechanics:

Easy stuff first! 

#### The Time Dependent Schroedinger Equation:

$$i\hbar \frac{\partial \Psi}{\partial t} = -\frac{\hbar^2}{2m}
\frac{\partial^2 \Psi}{\partial x^2} + V \Psi$$

This equation is a PDE, where the wavefunction $\Psi(\hat{r}, t)$ is function of both position and time. 

The Hamiltonian operator $\hat{H}$ represents the classical total energy of a quantum system (Kinetic + Potential).

In operator form:

$$\hat{H}\Psi=E\ \Psi$$

By assuming that the wave function can be expressed as the product of two functions, $\psi(\hat{r})$ and $\phi(t)$, separation of variables can be employed and the separation constant C of the time independent equition represents the allowed energies (eigenenergies) of the operator $\hat{H}$.

It is often favorable to represent the operator $\hat{H}$ in terms of its **eigenvectors** where the resultant matrix consists of all off-diagonal elements equal to zero and the diagonal formed by the eigenenergies.

Let's build a simple neural net from scratch with a relu activation function.

In [22]:
data = np.array([[0,0], [0,1], [1,0], [1,1]])
Qobj(data)

Quantum object: dims = [[4], [2]], shape = (4, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]

In [23]:
target = np.array([[0],[1],[1],[1]])
Qobj(target)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [1.]
 [1.]]

In [28]:
start_weights = np.array([[0.2], [0.8]])
Qobj(start_weights)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.2]
 [0.8]]

In [29]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def activation(x):
    return sigmoid(x)

In [30]:
def sigmoid_prime(x):
    return sigmoid(x)*(1-sigmoid(x))

In [31]:
def activation_prime(x):
    return sigmoid_prime(x)

In [32]:
n_iters = 10000

In [42]:
##
weights = start_weights
bias = 0.5
lr = 0.10
for x in range(n_iters):
    inputs = Qobj(data)
    #print(inputs)
    in_o = inputs * Qobj(weights) + bias
    #print(in_o)
    out_o = Qobj(activation(in_o))
    #print(out_o)
    error = out_o - Qobj(target)
    x = sum(error)
    #print(x)

    derror_douto = error

    douto_dino = Qobj(activation_prime(out_o))

    #print(douto_dino)
    #print(derror_douto)
    deriv = derror_douto
    for x, d in enumerate(deriv):  #does this do a hadamard product/
        deriv.data[x] *= douto_dino.data[x]

    #print(deriv)

    inputs = inputs.trans()
    #print(inputs)
    deriv_final = inputs * deriv
    #print(deriv_final)
    test = lr * deriv_final
    #print(test)
    weights -= lr * deriv_final

    for i in deriv:
        #print(i)
        #print(lr * 1)
        bias -= lr * i
    print(f'''
        Weight 1: {weights.data[0]} 
        Weight 2: {weights.data[1]}
        Bias: {bias}''',
          end='\r')

    #print(f'bias :{bias}')
    #deriv_final = inputs * deriv


        Weight 1:   (0, 0)	(0.21131020899441305+0j) 
        Weight 2:   (0, 0)	(0.8084817549043166+0j)
        Bias: [[0.50416575+0.j]]
        Weight 1:   (0, 0)	(0.2224550439272752+0j) 
        Weight 2:   (0, 0)	(0.8168337087799028+0j)
        Bias: [[0.50811689+0.j]]
        Weight 1:   (0, 0)	(0.23344024350914888+0j) 
        Weight 2:   (0, 0)	(0.8250606979363471+0j)
        Bias: [[0.51186091+0.j]]
        Weight 1:   (0, 0)	(0.24427127841337115+0j) 
        Weight 2:   (0, 0)	(0.8331673177443119+0j)
        Bias: [[0.51540495+0.j]]
        Weight 1:   (0, 0)	(0.2549533664845953+0j) 
        Weight 2:   (0, 0)	(0.8411579373022411+0j)
        Bias: [[0.51875582+0.j]]
        Weight 1:   (0, 0)	(0.26549148698167857+0j) 
        Weight 2:   (0, 0)	(0.8490367130897093+0j)
        Bias: [[0.52192+0.j]]
        Weight 1:   (0, 0)	(0.27589039391753806+0j) 
        Weight 2:   (0, 0)	(0.8568076016817133+0j)
        Bias: [[0.52490371+0.j]]
        Weight 1:   (0, 0)	(0.286154628555191

        Bias: [[0.51124072+0.j]]
        Weight 1:   (0, 0)	(0.7486728928536766+0j) 
        Weight 2:   (0, 0)	(1.209612441400872+0j)
        Bias: [[0.50908587+0.j]]
        Weight 1:   (0, 0)	(0.7550377854003446+0j) 
        Weight 2:   (0, 0)	(1.2143960818915727+0j)
        Bias: [[0.50689254+0.j]]
        Weight 1:   (0, 0)	(0.7613723973582242+0j) 
        Weight 2:   (0, 0)	(1.2191587649526652+0j)
        Bias: [[0.50466151+0.j]]
        Weight 1:   (0, 0)	(0.7676772889055653+0j) 
        Weight 2:   (0, 0)	(1.2239009152716407+0j)
        Bias: [[0.50239351+0.j]]
        Weight 1:   (0, 0)	(0.7739530062403208+0j) 
        Weight 2:   (0, 0)	(1.2286229466654468+0j)
        Bias: [[0.50008926+0.j]]
        Weight 1:   (0, 0)	(0.780200082027168+0j) 
        Weight 2:   (0, 0)	(1.233325262438529+0j)
        Bias: [[0.49774948+0.j]]
        Weight 1:   (0, 0)	(0.7864190358270725+0j) 
        Weight 2:   (0, 0)	(1.2380082557264374+0j)
        Bias: [[0.49537486+0.j]]
        Weight 1: 

        Bias: [[0.30064388+0.j]]
        Weight 1:   (0, 0)	(1.137620551457043+0j) 
        Weight 2:   (0, 0)	(1.5061830603541366+0j)
        Bias: [[0.29697487+0.j]]
        Weight 1:   (0, 0)	(1.1427330028885943+0j) 
        Weight 2:   (0, 0)	(1.510149590570783+0j)
        Bias: [[0.29329455+0.j]]
        Weight 1:   (0, 0)	(1.1478350851663837+0j) 
        Weight 2:   (0, 0)	(1.5141100766409947+0j)
        Bias: [[0.28960309+0.j]]
        Weight 1:   (0, 0)	(1.1529269333458407+0j) 
        Weight 2:   (0, 0)	(1.5180646182903117+0j)
        Bias: [[0.28590067+0.j]]
        Weight 1:   (0, 0)	(1.158008680193338+0j) 
        Weight 2:   (0, 0)	(1.5220133135284217+0j)
        Bias: [[0.28218747+0.j]]
        Weight 1:   (0, 0)	(1.163080456234529+0j) 
        Weight 2:   (0, 0)	(1.5259562586856659+0j)
        Bias: [[0.27846367+0.j]]
        Weight 1:   (0, 0)	(1.1681423898014371+0j) 
        Weight 2:   (0, 0)	(1.5298935484485827+0j)
        Bias: [[0.27472945+0.j]]
        Weight 1:  

        Bias: [[0.02431061+0.j]]
        Weight 1:   (0, 0)	(1.4762019489476335+0j) 
        Weight 2:   (0, 0)	(1.7734731392816705+0j)
        Bias: [[0.02016745+0.j]]
        Weight 1:   (0, 0)	(1.4808224114111095+0j) 
        Weight 2:   (0, 0)	(1.7771882898833247+0j)
        Bias: [[0.01602078+0.j]]
        Weight 1:   (0, 0)	(1.4854382654922875+0j) 
        Weight 2:   (0, 0)	(1.780901611147352+0j)
        Bias: [[0.01187068+0.j]]
        Weight 1:   (0, 0)	(1.490049558141209+0j) 
        Weight 2:   (0, 0)	(1.784613136769038+0j)
        Bias: [[0.00771719+0.j]]
        Weight 1:   (0, 0)	(1.494656335679967+0j) 
        Weight 2:   (0, 0)	(1.7883228999699348+0j)
        Bias: [[0.00356038+0.j]]
        Weight 1:   (0, 0)	(1.4992586438127722+0j) 
        Weight 2:   (0, 0)	(1.7920309335053086+0j)
        Bias: [[-0.00059968+0.j]]
        Weight 1:   (0, 0)	(1.5038565276358264+0j) 
        Weight 2:   (0, 0)	(1.7957372696714486+0j)
        Bias: [[-0.00476295+0.j]]
        Weight 1:

        Bias: [[-0.26287314+0.j]]
        Weight 1:   (0, 0)	(1.7818244760572575+0j) 
        Weight 2:   (0, 0)	(2.023303720908901+0j)
        Bias: [[-0.26714744+0.j]]
        Weight 1:   (0, 0)	(1.7862136317314516+0j) 
        Weight 2:   (0, 0)	(2.026952364350832+0j)
        Bias: [[-0.27142248+0.j]]
        Weight 1:   (0, 0)	(1.790600324668276+0j) 
        Weight 2:   (0, 0)	(2.030600674515586+0j)
        Bias: [[-0.27569823+0.j]]
        Weight 1:   (0, 0)	(1.7949845750596936+0j) 
        Weight 2:   (0, 0)	(2.0342486646943425+0j)
        Bias: [[-0.27997468+0.j]]
        Weight 1:   (0, 0)	(1.79936640286773+0j) 
        Weight 2:   (0, 0)	(2.0378963479998373+0j)
        Bias: [[-0.2842518+0.j]]
        Weight 1:   (0, 0)	(1.8037458278275849+0j) 
        Weight 2:   (0, 0)	(2.0415437373686904+0j)
        Bias: [[-0.28852956+0.j]]
        Weight 1:   (0, 0)	(1.808122869450692+0j) 
        Weight 2:   (0, 0)	(2.045190845563706+0j)
        Bias: [[-0.29280794+0.j]]
        Weight 1

        Bias: [[-0.575637+0.j]]
        Weight 1:   (0, 0)	(2.096806079668717+0j) 
        Weight 2:   (0, 0)	(2.2894412082486384+0j)
        Bias: [[-0.57991822+0.j]]
        Weight 1:   (0, 0)	(2.1010570036976453+0j) 
        Weight 2:   (0, 0)	(2.2930914541136382+0j)
        Bias: [[-0.58419907+0.j]]
        Weight 1:   (0, 0)	(2.1053064862662945+0j) 
        Weight 2:   (0, 0)	(2.296741982529715+0j)
        Bias: [[-0.58847954+0.j]]
        Weight 1:   (0, 0)	(2.1095545366890334+0j) 
        Weight 2:   (0, 0)	(2.3003927982399586+0j)
        Bias: [[-0.59275962+0.j]]
        Weight 1:   (0, 0)	(2.113801164189892+0j) 
        Weight 2:   (0, 0)	(2.3040439059155498+0j)
        Bias: [[-0.59703929+0.j]]
        Weight 1:   (0, 0)	(2.1180463779036467+0j) 
        Weight 2:   (0, 0)	(2.3076953101566144+0j)
        Bias: [[-0.60131856+0.j]]
        Weight 1:   (0, 0)	(2.1222901868768895+0j) 
        Weight 2:   (0, 0)	(2.3113470154930678+0j)
        Bias: [[-0.60559742+0.j]]
        Weig

        Bias: [[-0.86133521+0.j]]
        Weight 1:   (0, 0)	(2.378817074234588+0j) 
        Weight 2:   (0, 0)	(2.534811810004736+0j)
        Bias: [[-0.86557799+0.j]]
        Weight 1:   (0, 0)	(2.382988396603857+0j) 
        Weight 2:   (0, 0)	(2.5384885943221365+0j)
        Bias: [[-0.86982006+0.j]]
        Weight 1:   (0, 0)	(2.3871587444330973+0j) 
        Weight 2:   (0, 0)	(2.542165854010027+0j)
        Bias: [[-0.87406142+0.j]]
        Weight 1:   (0, 0)	(2.3913281228223195+0j) 
        Weight 2:   (0, 0)	(2.545843590468775+0j)
        Bias: [[-0.87830206+0.j]]
        Weight 1:   (0, 0)	(2.3954965368298513+0j) 
        Weight 2:   (0, 0)	(2.549521805066264+0j)
        Bias: [[-0.88254198+0.j]]
        Weight 1:   (0, 0)	(2.399663991472793+0j) 
        Weight 2:   (0, 0)	(2.5532004991382795+0j)
        Bias: [[-0.88678118+0.j]]
        Weight 1:   (0, 0)	(2.403830491727469+0j) 
        Weight 2:   (0, 0)	(2.556879673988888+0j)
        Bias: [[-0.89101967+0.j]]
        Weight 1

        Bias: [[-1.14395565+0.j]]
        Weight 1:   (0, 0)	(2.6563572348626763+0j) 
        Weight 2:   (0, 0)	(2.7822529152823225+0j)
        Bias: [[-1.14814791+0.j]]
        Weight 1:   (0, 0)	(2.6604728442963324+0j) 
        Weight 2:   (0, 0)	(2.7859633472839596+0j)
        Bias: [[-1.1523394+0.j]]
        Weight 1:   (0, 0)	(2.664587746897038+0j) 
        Weight 2:   (0, 0)	(2.7896742922162012+0j)
        Bias: [[-1.15653012+0.j]]
        Weight 1:   (0, 0)	(2.6687019457593433+0j) 
        Weight 2:   (0, 0)	(2.793385749980534+0j)
        Bias: [[-1.16072007+0.j]]
        Weight 1:   (0, 0)	(2.6728154439571234+0j) 
        Weight 2:   (0, 0)	(2.7970977204642216+0j)
        Bias: [[-1.16490925+0.j]]
        Weight 1:   (0, 0)	(2.676928244543781+0j) 
        Weight 2:   (0, 0)	(2.8008102035404887+0j)
        Bias: [[-1.16909767+0.j]]
        Weight 1:   (0, 0)	(2.6810403505524465+0j) 
        Weight 2:   (0, 0)	(2.804523199068702+0j)
        Bias: [[-1.17328532+0.j]]
        Weig

        Bias: [[-1.43558956+0.j]]
        Weight 1:   (0, 0)	(2.9428955117133584+0j) 
        Weight 2:   (0, 0)	(3.0432054336871963+0j)
        Bias: [[-1.43972968+0.j]]
        Weight 1:   (0, 0)	(2.946968145405495+0j) 
        Weight 2:   (0, 0)	(3.0469509011635902+0j)
        Bias: [[-1.4438691+0.j]]
        Weight 1:   (0, 0)	(2.951040248209358+0j) 
        Weight 2:   (0, 0)	(3.050696848785691+0j)
        Bias: [[-1.44800781+0.j]]
        Weight 1:   (0, 0)	(2.9551118221559776+0j) 
        Weight 2:   (0, 0)	(3.054443275811244+0j)
        Bias: [[-1.45214581+0.j]]
        Weight 1:   (0, 0)	(2.9591828692655193+0j) 
        Weight 2:   (0, 0)	(3.058190181492823+0j)
        Bias: [[-1.45628311+0.j]]
        Weight 1:   (0, 0)	(2.963253391547374+0j) 
        Weight 2:   (0, 0)	(3.0619375650779146+0j)
        Bias: [[-1.4604197+0.j]]
        Weight 1:   (0, 0)	(2.9673233910002494+0j) 
        Weight 2:   (0, 0)	(3.0656854258090034+0j)
        Bias: [[-1.4645556+0.j]]
        Weight 1

        Bias: [[-1.71148114+0.j]]
        Weight 1:   (0, 0)	(3.21467793578475+0j) 
        Weight 2:   (0, 0)	(3.295174578867671+0j)
        Bias: [[-1.71557704+0.j]]
        Weight 1:   (0, 0)	(3.2187190315209047+0j) 
        Weight 2:   (0, 0)	(3.298950384917648+0j)
        Bias: [[-1.71967234+0.j]]
        Weight 1:   (0, 0)	(3.222759712137131+0j) 
        Weight 2:   (0, 0)	(3.302726613430553+0j)
        Bias: [[-1.72376703+0.j]]
        Weight 1:   (0, 0)	(3.226799979098463+0j) 
        Weight 2:   (0, 0)	(3.306503263469355+0j)
        Bias: [[-1.72786111+0.j]]
        Weight 1:   (0, 0)	(3.2308398338634534+0j) 
        Weight 2:   (0, 0)	(3.3102803340959386+0j)
        Bias: [[-1.73195459+0.j]]
        Weight 1:   (0, 0)	(3.234879277884218+0j) 
        Weight 2:   (0, 0)	(3.3140578243711434+0j)
        Bias: [[-1.73604747+0.j]]
        Weight 1:   (0, 0)	(3.2389183126064807+0j) 
        Weight 2:   (0, 0)	(3.3178357333548045+0j)
        Bias: [[-1.74013975+0.j]]
        Weight 1

        Bias: [[-1.99681235+0.j]]
        Weight 1:   (0, 0)	(3.4966268653110744+0j) 
        Weight 2:   (0, 0)	(3.5604493972255478+0j)
        Bias: [[-2.0008695+0.j]]
        Weight 1:   (0, 0)	(3.5006421222009574+0j) 
        Weight 2:   (0, 0)	(3.5642524854525792+0j)
        Bias: [[-2.00492615+0.j]]
        Weight 1:   (0, 0)	(3.5046570529683234+0j) 
        Weight 2:   (0, 0)	(3.568055929773005+0j)
        Bias: [[-2.0089823+0.j]]
        Weight 1:   (0, 0)	(3.508671658712263+0j) 
        Weight 2:   (0, 0)	(3.5718597292500074+0j)
        Bias: [[-2.01303795+0.j]]
        Weight 1:   (0, 0)	(3.512685940527673+0j) 
        Weight 2:   (0, 0)	(3.575663882947613+0j)
        Bias: [[-2.01709311+0.j]]
        Weight 1:   (0, 0)	(3.5166998995052783+0j) 
        Weight 2:   (0, 0)	(3.5794683899307103+0j)
        Bias: [[-2.02114778+0.j]]
        Weight 1:   (0, 0)	(3.520713536731656+0j) 
        Weight 2:   (0, 0)	(3.5832732492650665+0j)
        Bias: [[-2.02520196+0.j]]
        Weight

        Bias: [[-2.29579015+0.j]]
        Weight 1:   (0, 0)	(3.7929417774554275+0j) 
        Weight 2:   (0, 0)	(3.842780212866093+0j)
        Bias: [[-2.29981434+0.j]]
        Weight 1:   (0, 0)	(3.796935621690738+0j) 
        Weight 2:   (0, 0)	(3.8466071926540106+0j)
        Bias: [[-2.30383814+0.j]]
        Weight 1:   (0, 0)	(3.8009292111020003+0j) 
        Weight 2:   (0, 0)	(3.8504344623628604+0j)
        Bias: [[-2.30786154+0.j]]
        Weight 1:   (0, 0)	(3.8049225465293426+0j) 
        Weight 2:   (0, 0)	(3.8542620211516776+0j)
        Bias: [[-2.31188455+0.j]]
        Weight 1:   (0, 0)	(3.8089156288099795+0j) 
        Weight 2:   (0, 0)	(3.8580898681811067+0j)
        Bias: [[-2.31590717+0.j]]
        Weight 1:   (0, 0)	(3.8129084587782245+0j) 
        Weight 2:   (0, 0)	(3.8619180026134066+0j)
        Bias: [[-2.31992941+0.j]]
        Weight 1:   (0, 0)	(3.816901037265504+0j) 
        Weight 2:   (0, 0)	(3.865746423612456+0j)
        Bias: [[-2.32395126+0.j]]
        Wei

        Bias: [[-2.56060047+0.j]]
        Weight 1:   (0, 0)	(4.0560253506046715+0j) 
        Weight 2:   (0, 0)	(4.095945472963748+0j)
        Bias: [[-2.56460136+0.j]]
        Weight 1:   (0, 0)	(4.0600040536918724+0j) 
        Weight 2:   (0, 0)	(4.099789860095132+0j)
        Bias: [[-2.56860194+0.j]]
        Weight 1:   (0, 0)	(4.063982551681451+0j) 
        Weight 2:   (0, 0)	(4.103634485259602+0j)
        Bias: [[-2.5726022+0.j]]
        Weight 1:   (0, 0)	(4.067960845245118+0j) 
        Weight 2:   (0, 0)	(4.107479347729106+0j)
        Bias: [[-2.57660215+0.j]]
        Weight 1:   (0, 0)	(4.071938935052358+0j) 
        Weight 2:   (0, 0)	(4.111324446777351+0j)
        Bias: [[-2.58060179+0.j]]
        Weight 1:   (0, 0)	(4.075916821770434+0j) 
        Weight 2:   (0, 0)	(4.115169781679806+0j)
        Bias: [[-2.58460112+0.j]]
        Weight 1:   (0, 0)	(4.079894506064402+0j) 
        Weight 2:   (0, 0)	(4.119015351713698+0j)
        Bias: [[-2.58860015+0.j]]
        Weight 1:   

        Bias: [[-2.83199853+0.j]]
        Weight 1:   (0, 0)	(4.326141880187415+0j) 
        Weight 2:   (0, 0)	(4.357870978559334+0j)
        Bias: [[-2.83598043+0.j]]
        Weight 1:   (0, 0)	(4.330108061541462+0j) 
        Weight 2:   (0, 0)	(4.361729981183434+0j)
        Bias: [[-2.83996207+0.j]]
        Weight 1:   (0, 0)	(4.334074078786037+0j) 
        Weight 2:   (0, 0)	(4.365589176307724+0j)
        Bias: [[-2.84394348+0.j]]
        Weight 1:   (0, 0)	(4.338039932458442+0j) 
        Weight 2:   (0, 0)	(4.369448563321791+0j)
        Bias: [[-2.84792463+0.j]]
        Weight 1:   (0, 0)	(4.342005623094235+0j) 
        Weight 2:   (0, 0)	(4.373308141616893+0j)
        Bias: [[-2.85190555+0.j]]
        Weight 1:   (0, 0)	(4.34597115122723+0j) 
        Weight 2:   (0, 0)	(4.377167910585959+0j)
        Bias: [[-2.85588622+0.j]]
        Weight 1:   (0, 0)	(4.34993651738951+0j) 
        Weight 2:   (0, 0)	(4.381027869623586+0j)
        Bias: [[-2.85986665+0.j]]
        Weight 1:   (0,

        Bias: [[-3.11018258+0.j]]
        Weight 1:   (0, 0)	(4.6034061306972065+0j) 
        Weight 2:   (0, 0)	(4.6284341401429945+0j)
        Bias: [[-3.11414924+0.j]]
        Weight 1:   (0, 0)	(4.607362031577949+0j) 
        Weight 2:   (0, 0)	(4.632305232907771+0j)
        Bias: [[-3.1181157+0.j]]
        Weight 1:   (0, 0)	(4.611317802048567+0j) 
        Weight 2:   (0, 0)	(4.636176479343759+0j)
        Bias: [[-3.12208198+0.j]]
        Weight 1:   (0, 0)	(4.6152734425372675+0j) 
        Weight 2:   (0, 0)	(4.6400478789512745+0j)
        Bias: [[-3.12604806+0.j]]
        Weight 1:   (0, 0)	(4.619228953470876+0j) 
        Weight 2:   (0, 0)	(4.643919431232108+0j)
        Bias: [[-3.13001396+0.j]]
        Weight 1:   (0, 0)	(4.623184335274839+0j) 
        Weight 2:   (0, 0)	(4.647791135689527+0j)
        Bias: [[-3.13397967+0.j]]
        Weight 1:   (0, 0)	(4.62713958837323+0j) 
        Weight 2:   (0, 0)	(4.651662991828271+0j)
        Bias: [[-3.13794519+0.j]]
        Weight 1:  

        Bias: [[-3.39533449+0.j]]
        Weight 1:   (0, 0)	(4.887921841578499+0j) 
        Weight 2:   (0, 0)	(4.9075172779316825+0j)
        Bias: [[-3.39928909+0.j]]
        Weight 1:   (0, 0)	(4.891869369340873+0j) 
        Weight 2:   (0, 0)	(4.911398242717488+0j)
        Bias: [[-3.40324355+0.j]]
        Weight 1:   (0, 0)	(4.895816794240698+0j) 
        Weight 2:   (0, 0)	(4.915279328785473+0j)
        Bias: [[-3.40719786+0.j]]
        Weight 1:   (0, 0)	(4.899764116617167+0j) 
        Weight 2:   (0, 0)	(4.919160535734217+0j)
        Bias: [[-3.41115203+0.j]]
        Weight 1:   (0, 0)	(4.903711336808375+0j) 
        Weight 2:   (0, 0)	(4.923041863163548+0j)
        Bias: [[-3.41510605+0.j]]
        Weight 1:   (0, 0)	(4.907658455151324+0j) 
        Weight 2:   (0, 0)	(4.926923310674539+0j)
        Bias: [[-3.41905993+0.j]]
        Weight 1:   (0, 0)	(4.911605471981924+0j) 
        Weight 2:   (0, 0)	(4.930804877869503+0j)
        Bias: [[-3.42301367+0.j]]
        Weight 1:   

        Bias: [[-3.68367006+0.j]]
        Weight 1:   (0, 0)	(5.1758409978454445+0j) 
        Weight 2:   (0, 0)	(5.191122780338457+0j)
        Bias: [[-3.68761536+0.j]]
        Weight 1:   (0, 0)	(5.179781843412141+0j) 
        Weight 2:   (0, 0)	(5.1950116179390635+0j)
        Bias: [[-3.69156055+0.j]]
        Weight 1:   (0, 0)	(5.183722608198273+0j) 
        Weight 2:   (0, 0)	(5.198900550600736+0j)
        Bias: [[-3.69550564+0.j]]
        Weight 1:   (0, 0)	(5.187663292471416+0j) 
        Weight 2:   (0, 0)	(5.2027895780049045+0j)
        Bias: [[-3.69945061+0.j]]
        Weight 1:   (0, 0)	(5.191603896498277+0j) 
        Weight 2:   (0, 0)	(5.206678699834023+0j)
        Bias: [[-3.70339547+0.j]]
        Weight 1:   (0, 0)	(5.195544420544697+0j) 
        Weight 2:   (0, 0)	(5.2105679157715645+0j)
        Bias: [[-3.70734023+0.j]]
        Weight 1:   (0, 0)	(5.199484864875649+0j) 
        Weight 2:   (0, 0)	(5.214457225502021+0j)
        Bias: [[-3.71128487+0.j]]
        Weight 1:

        Bias: [[-3.94384144+0.j]]
        Weight 1:   (0, 0)	(5.435775171926492+0j) 
        Weight 2:   (0, 0)	(5.447976101848413+0j)
        Bias: [[-3.94778029+0.j]]
        Weight 1:   (0, 0)	(5.439711222018418+0j) 
        Weight 2:   (0, 0)	(5.451870574900273+0j)
        Bias: [[-3.95171906+0.j]]
        Weight 1:   (0, 0)	(5.443647207243389+0j) 
        Weight 2:   (0, 0)	(5.4557651240521+0j)
        Bias: [[-3.95565774+0.j]]
        Weight 1:   (0, 0)	(5.447583127817088+0j) 
        Weight 2:   (0, 0)	(5.459659749046827+0j)
        Bias: [[-3.95959634+0.j]]
        Weight 1:   (0, 0)	(5.451518983954491+0j) 
        Weight 2:   (0, 0)	(5.463554449628229+0j)
        Bias: [[-3.96353485+0.j]]
        Weight 1:   (0, 0)	(5.455454775869872+0j) 
        Weight 2:   (0, 0)	(5.467449225540923+0j)
        Bias: [[-3.96747328+0.j]]
        Weight 1:   (0, 0)	(5.459390503776802+0j) 
        Weight 2:   (0, 0)	(5.47134407653036+0j)
        Bias: [[-3.97141162+0.j]]
        Weight 1:   (0, 

        Bias: [[-4.23510492+0.j]]
        Weight 1:   (0, 0)	(5.726880877715802+0j) 
        Weight 2:   (0, 0)	(5.736356918793179+0j)
        Bias: [[-4.23903824+0.j]]
        Weight 1:   (0, 0)	(5.730812666959119+0j) 
        Weight 2:   (0, 0)	(5.740256380668883+0j)
        Bias: [[-4.2429715+0.j]]
        Weight 1:   (0, 0)	(5.734744405528616+0j) 
        Weight 2:   (0, 0)	(5.744155901738295+0j)
        Bias: [[-4.24690469+0.j]]
        Weight 1:   (0, 0)	(5.738676093593417+0j) 
        Weight 2:   (0, 0)	(5.748055481800182+0j)
        Bias: [[-4.25083782+0.j]]
        Weight 1:   (0, 0)	(5.7426077313220905+0j) 
        Weight 2:   (0, 0)	(5.75195512065398+0j)
        Bias: [[-4.25477089+0.j]]
        Weight 1:   (0, 0)	(5.746539318882649+0j) 
        Weight 2:   (0, 0)	(5.7558548180997935+0j)
        Bias: [[-4.25870389+0.j]]
        Weight 1:   (0, 0)	(5.750470856442552+0j) 
        Weight 2:   (0, 0)	(5.759754573938392+0j)
        Bias: [[-4.26263682+0.j]]
        Weight 1:   (

        Bias: [[-4.50636509+0.j]]
        Weight 1:   (0, 0)	(5.998063854142789+0j) 
        Weight 2:   (0, 0)	(6.005548669221503+0j)
        Bias: [[-4.5102945+0.j]]
        Weight 1:   (0, 0)	(6.0019925159842185+0j) 
        Weight 2:   (0, 0)	(6.0094517767006+0j)
        Bias: [[-4.51422386+0.j]]
        Weight 1:   (0, 0)	(6.005921137604829+0j) 
        Weight 2:   (0, 0)	(6.013354930953842+0j)
        Bias: [[-4.51815317+0.j]]
        Weight 1:   (0, 0)	(6.009849719139261+0j) 
        Weight 2:   (0, 0)	(6.017258131821548+0j)
        Bias: [[-4.52208243+0.j]]
        Weight 1:   (0, 0)	(6.01377826072171+0j) 
        Weight 2:   (0, 0)	(6.021161379144576+0j)
        Bias: [[-4.52601165+0.j]]
        Weight 1:   (0, 0)	(6.017706762485928+0j) 
        Weight 2:   (0, 0)	(6.0250646727643185+0j)
        Bias: [[-4.52994081+0.j]]
        Weight 1:   (0, 0)	(6.021635224565223+0j) 
        Weight 2:   (0, 0)	(6.028968012522699+0j)
        Bias: [[-4.53386993+0.j]]
        Weight 1:   (0,

        Bias: [[-4.78131438+0.j]]
        Weight 1:   (0, 0)	(6.272980028546334+0j) 
        Weight 2:   (0, 0)	(6.278870883406946+0j)
        Bias: [[-4.78524076+0.j]]
        Weight 1:   (0, 0)	(6.276906176979217+0j) 
        Weight 2:   (0, 0)	(6.282776907309805+0j)
        Bias: [[-4.7891671+0.j]]
        Weight 1:   (0, 0)	(6.280832293615597+0j) 
        Weight 2:   (0, 0)	(6.2866829680154055+0j)
        Bias: [[-4.79309341+0.j]]
        Weight 1:   (0, 0)	(6.284758378562187+0j) 
        Weight 2:   (0, 0)	(6.290589065397725+0j)
        Bias: [[-4.79701967+0.j]]
        Weight 1:   (0, 0)	(6.288684431925348+0j) 
        Weight 2:   (0, 0)	(6.2944951993311715+0j)
        Bias: [[-4.8009459+0.j]]
        Weight 1:   (0, 0)	(6.292610453811086+0j) 
        Weight 2:   (0, 0)	(6.298401369690575+0j)
        Bias: [[-4.80487209+0.j]]
        Weight 1:   (0, 0)	(6.296536444325056+0j) 
        Weight 2:   (0, 0)	(6.302307576351193+0j)
        Bias: [[-4.80879825+0.j]]
        Weight 1:   (

        Bias: [[-5.06000162+0.j]]
        Weight 1:   (0, 0)	(6.551663322278209+0j) 
        Weight 2:   (0, 0)	(6.556283229737083+0j)
        Bias: [[-5.06392566+0.j]]
        Weight 1:   (0, 0)	(6.555587459157456+0j) 
        Weight 2:   (0, 0)	(6.560191576563096+0j)
        Bias: [[-5.06784967+0.j]]
        Weight 1:   (0, 0)	(6.559511570998533+0j) 
        Weight 2:   (0, 0)	(6.564099952228977+0j)
        Bias: [[-5.07177366+0.j]]
        Weight 1:   (0, 0)	(6.563435657885656+0j) 
        Weight 2:   (0, 0)	(6.568008356635759+0j)
        Bias: [[-5.07569761+0.j]]
        Weight 1:   (0, 0)	(6.56735971990276+0j) 
        Weight 2:   (0, 0)	(6.57191678968481+0j)
        Bias: [[-5.07962154+0.j]]
        Weight 1:   (0, 0)	(6.571283757133501+0j) 
        Weight 2:   (0, 0)	(6.575825251277835+0j)
        Bias: [[-5.08354544+0.j]]
        Weight 1:   (0, 0)	(6.575207769661255+0j) 
        Weight 2:   (0, 0)	(6.579733741316874+0j)
        Bias: [[-5.08746931+0.j]]
        Weight 1:   (0,

        Bias: [[-5.3463881+0.j]]
        Weight 1:   (0, 0)	(6.838064459697032+0j) 
        Weight 2:   (0, 0)	(6.841662534378945+0j)
        Bias: [[-5.35031032+0.j]]
        Weight 1:   (0, 0)	(6.841986973600754+0j) 
        Weight 2:   (0, 0)	(6.845572746219951+0j)
        Bias: [[-5.35423253+0.j]]
        Weight 1:   (0, 0)	(6.845909467930196+0j) 
        Weight 2:   (0, 0)	(6.849482980495767+0j)
        Bias: [[-5.35815471+0.j]]
        Weight 1:   (0, 0)	(6.849831942751319+0j) 
        Weight 2:   (0, 0)	(6.853393237129286+0j)
        Bias: [[-5.36207687+0.j]]
        Weight 1:   (0, 0)	(6.853754398129864+0j) 
        Weight 2:   (0, 0)	(6.857303516043662+0j)
        Bias: [[-5.36599901+0.j]]
        Weight 1:   (0, 0)	(6.857676834131351+0j) 
        Weight 2:   (0, 0)	(6.861213817162316+0j)
        Bias: [[-5.36992113+0.j]]
        Weight 1:   (0, 0)	(6.861599250821083+0j) 
        Weight 2:   (0, 0)	(6.865124140408929+0j)
        Bias: [[-5.37384323+0.j]]
        Weight 1:   (0

        Bias: [[-5.61305447+0.j]]
        Weight 1:   (0, 0)	(7.104753948246018+0j) 
        Weight 2:   (0, 0)	(7.107604387528654+0j)
        Bias: [[-5.61697541+0.j]]
        Weight 1:   (0, 0)	(7.108675270866324+0j) 
        Weight 2:   (0, 0)	(7.111515961805734+0j)
        Bias: [[-5.62089634+0.j]]
        Weight 1:   (0, 0)	(7.112596577929586+0j) 
        Weight 2:   (0, 0)	(7.11542755383268+0j)
        Bias: [[-5.62481725+0.j]]
        Weight 1:   (0, 0)	(7.1165178694883044+0j) 
        Weight 2:   (0, 0)	(7.119339163548424+0j)
        Bias: [[-5.62873814+0.j]]
        Weight 1:   (0, 0)	(7.120439145594803+0j) 
        Weight 2:   (0, 0)	(7.1232507908921106+0j)
        Bias: [[-5.63265902+0.j]]
        Weight 1:   (0, 0)	(7.124360406301231+0j) 
        Weight 2:   (0, 0)	(7.127162435803093+0j)
        Bias: [[-5.63657987+0.j]]
        Weight 1:   (0, 0)	(7.128281651659562+0j) 
        Weight 2:   (0, 0)	(7.131074098220932+0j)
        Bias: [[-5.64050072+0.j]]
        Weight 1:   

        Bias: [[-5.88356398+0.j]]
        Weight 1:   (0, 0)	(7.375291316992197+0j) 
        Weight 2:   (0, 0)	(7.37754162764847+0j)
        Bias: [[-5.88748393+0.j]]
        Weight 1:   (0, 0)	(7.379211680597907+0j) 
        Weight 2:   (0, 0)	(7.38145429378712+0j)
        Bias: [[-5.89140386+0.j]]
        Weight 1:   (0, 0)	(7.38313203188491+0j) 
        Weight 2:   (0, 0)	(7.385366973917989+0j)
        Bias: [[-5.89532378+0.j]]
        Weight 1:   (0, 0)	(7.387052370894829+0j) 
        Weight 2:   (0, 0)	(7.389279667992909+0j)
        Bias: [[-5.89924368+0.j]]
        Weight 1:   (0, 0)	(7.390972697669149+0j) 
        Weight 2:   (0, 0)	(7.393192375963875+0j)
        Bias: [[-5.90316358+0.j]]
        Weight 1:   (0, 0)	(7.394893012249212+0j) 
        Weight 2:   (0, 0)	(7.397105097783046+0j)
        Bias: [[-5.90708346+0.j]]
        Weight 1:   (0, 0)	(7.398813314676223+0j) 
        Weight 2:   (0, 0)	(7.401017833402748+0j)
        Bias: [[-5.91100333+0.j]]
        Weight 1:   (0, 

        Bias: [[-6.1657706+0.j]]
        Weight 1:   (0, 0)	(7.657528354712965+0j) 
        Weight 2:   (0, 0)	(7.659286643484698+0j)
        Bias: [[-6.16968975+0.j]]
        Weight 1:   (0, 0)	(7.661447929873269+0j) 
        Weight 2:   (0, 0)	(7.663200203252798+0j)
        Bias: [[-6.1736089+0.j]]
        Weight 1:   (0, 0)	(7.665367495380332+0j) 
        Weight 2:   (0, 0)	(7.667113773935967+0j)
        Bias: [[-6.17752804+0.j]]
        Weight 1:   (0, 0)	(7.6692870512668065+0j) 
        Weight 2:   (0, 0)	(7.671027355496611+0j)
        Bias: [[-6.18144716+0.j]]
        Weight 1:   (0, 0)	(7.673206597565235+0j) 
        Weight 2:   (0, 0)	(7.674940947897267+0j)
        Bias: [[-6.18536628+0.j]]
        Weight 1:   (0, 0)	(7.6771261343080495+0j) 
        Weight 2:   (0, 0)	(7.6788545511005974+0j)
        Bias: [[-6.18928539+0.j]]
        Weight 1:   (0, 0)	(7.681045661527574+0j) 
        Weight 2:   (0, 0)	(7.682768165069397+0j)
        Bias: [[-6.19320448+0.j]]
        Weight 1:   

        Bias: [[-6.42833466+0.j]]
        Weight 1:   (0, 0)	(7.920120030476903+0j) 
        Weight 2:   (0, 0)	(7.921517575225012+0j)
        Bias: [[-6.43225325+0.j]]
        Weight 1:   (0, 0)	(7.924039026065811+0j) 
        Weight 2:   (0, 0)	(7.925431789052341+0j)
        Bias: [[-6.43617184+0.j]]
        Weight 1:   (0, 0)	(7.927958013962718+0j) 
        Weight 2:   (0, 0)	(7.929346011541753+0j)
        Bias: [[-6.44009042+0.j]]
        Weight 1:   (0, 0)	(7.931876994193664+0j) 
        Weight 2:   (0, 0)	(7.9332602426634065+0j)
        Bias: [[-6.44400899+0.j]]
        Weight 1:   (0, 0)	(7.935795966784601+0j) 
        Weight 2:   (0, 0)	(7.9371744823875625+0j)
        Bias: [[-6.44792756+0.j]]
        Weight 1:   (0, 0)	(7.9397149317613955+0j) 
        Weight 2:   (0, 0)	(7.941088730684585+0j)
        Bias: [[-6.45184612+0.j]]
        Weight 1:   (0, 0)	(7.943633889149825+0j) 
        Weight 2:   (0, 0)	(7.9450029875249415+0j)
        Bias: [[-6.45576467+0.j]]
        Weight 1:

        Bias: [[-6.70653828+0.j]]
        Weight 1:   (0, 0)	(8.198351009363057+0j) 
        Weight 2:   (0, 0)	(8.199446672058615+0j)
        Bias: [[-6.71045642+0.j]]
        Weight 1:   (0, 0)	(8.202269518783858+0j) 
        Weight 2:   (0, 0)	(8.20336143228235+0j)
        Bias: [[-6.71437456+0.j]]
        Weight 1:   (0, 0)	(8.206188022159166+0j) 
        Weight 2:   (0, 0)	(8.207276199285682+0j)
        Bias: [[-6.71829269+0.j]]
        Weight 1:   (0, 0)	(8.210106519509464+0j) 
        Weight 2:   (0, 0)	(8.211190973045253+0j)
        Bias: [[-6.72221082+0.j]]
        Weight 1:   (0, 0)	(8.214025010855167+0j) 
        Weight 2:   (0, 0)	(8.215105753537786+0j)
        Bias: [[-6.72612894+0.j]]
        Weight 1:   (0, 0)	(8.217943496216616+0j) 
        Weight 2:   (0, 0)	(8.21902054074008+0j)
        Bias: [[-6.73004705+0.j]]
        Weight 1:   (0, 0)	(8.221861975614088+0j) 
        Weight 2:   (0, 0)	(8.22293533462902+0j)
        Bias: [[-6.73396516+0.j]]
        Weight 1:   (0, 

        Bias: [[-6.96904254+0.j]]
        Weight 1:   (0, 0)	(8.460878704323198+0j) 
        Weight 2:   (0, 0)	(8.461749536818829+0j)
        Bias: [[-6.97296035+0.j]]
        Weight 1:   (0, 0)	(8.464796850839205+0j) 
        Weight 2:   (0, 0)	(8.465664703280115+0j)
        Bias: [[-6.97687816+0.j]]
        Weight 1:   (0, 0)	(8.468714992539638+0j) 
        Weight 2:   (0, 0)	(8.469579875121285+0j)
        Bias: [[-6.98079597+0.j]]
        Weight 1:   (0, 0)	(8.472633129440823+0j) 
        Weight 2:   (0, 0)	(8.473495052323802+0j)
        Bias: [[-6.98471377+0.j]]
        Weight 1:   (0, 0)	(8.476551261559027+0j) 
        Weight 2:   (0, 0)	(8.477410234869193+0j)
        Bias: [[-6.98863157+0.j]]
        Weight 1:   (0, 0)	(8.48046938891047+0j) 
        Weight 2:   (0, 0)	(8.481325422739049+0j)
        Bias: [[-6.99254937+0.j]]
        Weight 1:   (0, 0)	(8.484387511511308+0j) 
        Weight 2:   (0, 0)	(8.485240615915023+0j)
        Bias: [[-6.99646716+0.j]]
        Weight 1:   (0

        Bias: [[-7.24328022+0.j]]
        Weight 1:   (0, 0)	(8.735138176053825+0j) 
        Weight 2:   (0, 0)	(8.735823222816089+0j)
        Bias: [[-7.24719777+0.j]]
        Weight 1:   (0, 0)	(8.739056022047473+0j) 
        Weight 2:   (0, 0)	(8.739738724406132+0j)
        Bias: [[-7.25111532+0.j]]
        Weight 1:   (0, 0)	(8.742973864244657+0j) 
        Weight 2:   (0, 0)	(8.743654230221352+0j)
        Bias: [[-7.25503287+0.j]]
        Weight 1:   (0, 0)	(8.746891702658257+0j) 
        Weight 2:   (0, 0)	(8.74756974024719+0j)
        Bias: [[-7.25895042+0.j]]
        Weight 1:   (0, 0)	(8.750809537301103+0j) 
        Weight 2:   (0, 0)	(8.751485254469138+0j)
        Bias: [[-7.26286796+0.j]]
        Weight 1:   (0, 0)	(8.754727368185991+0j) 
        Weight 2:   (0, 0)	(8.75540077287274+0j)
        Bias: [[-7.2667855+0.j]]
        Weight 1:   (0, 0)	(8.758645195325666+0j) 
        Weight 2:   (0, 0)	(8.759316295443586+0j)
        Bias: [[-7.27070303+0.j]]
        Weight 1:   (0, 

        Bias: [[-7.52925397+0.j]]
        Weight 1:   (0, 0)	(9.021131712136258+0j) 
        Weight 2:   (0, 0)	(9.02166508932279+0j)
        Bias: [[-7.53317132+0.j]]
        Weight 1:   (0, 0)	(9.025049312273701+0j) 
        Weight 2:   (0, 0)	(9.02558086403363+0j)
        Bias: [[-7.53708866+0.j]]
        Weight 1:   (0, 0)	(9.028966909448869+0j) 
        Weight 2:   (0, 0)	(9.029496642028644+0j)
        Bias: [[-7.54100601+0.j]]
        Weight 1:   (0, 0)	(9.032884503671813+0j) 
        Weight 2:   (0, 0)	(9.033412423296515+0j)
        Bias: [[-7.54492335+0.j]]
        Weight 1:   (0, 0)	(9.036802094952554+0j) 
        Weight 2:   (0, 0)	(9.037328207825968+0j)
        Bias: [[-7.54884069+0.j]]
        Weight 1:   (0, 0)	(9.040719683301079+0j) 
        Weight 2:   (0, 0)	(9.041243995605768+0j)
        Bias: [[-7.55275803+0.j]]
        Weight 1:   (0, 0)	(9.044637268727339+0j) 
        Weight 2:   (0, 0)	(9.045159786624716+0j)
        Bias: [[-7.55667536+0.j]]
        Weight 1:   (0,

        Bias: [[-7.79954585+0.j]]
        Weight 1:   (0, 0)	(9.29143967068066+0j) 
        Weight 2:   (0, 0)	(9.291860688475417+0j)
        Bias: [[-7.80346305+0.j]]
        Weight 1:   (0, 0)	(9.295357088317996+0j) 
        Weight 2:   (0, 0)	(9.295776665182004+0j)
        Bias: [[-7.80738025+0.j]]
        Weight 1:   (0, 0)	(9.299274503612574+0j) 
        Weight 2:   (0, 0)	(9.29969264447688+0j)
        Bias: [[-7.81129745+0.j]]
        Weight 1:   (0, 0)	(9.30319191657235+0j) 
        Weight 2:   (0, 0)	(9.303608626351128+0j)
        Bias: [[-7.81521465+0.j]]
        Weight 1:   (0, 0)	(9.307109327205252+0j) 
        Weight 2:   (0, 0)	(9.307524610795864+0j)
        Bias: [[-7.81913184+0.j]]
        Weight 1:   (0, 0)	(9.311026735519178+0j) 
        Weight 2:   (0, 0)	(9.311440597802234+0j)
        Bias: [[-7.82304904+0.j]]
        Weight 1:   (0, 0)	(9.314944141522004+0j) 
        Weight 2:   (0, 0)	(9.31535658736141+0j)
        Bias: [[-7.82696623+0.j]]
        Weight 1:   (0, 0

        Bias: [[-8.04240915+0.j]]
        Weight 1:   (0, 0)	(9.534315420414213+0j) 
        Weight 2:   (0, 0)	(9.534655818006812+0j)
        Bias: [[-8.04632625+0.j]]
        Weight 1:   (0, 0)	(9.538232706871918+0j) 
        Weight 2:   (0, 0)	(9.538571939432197+0j)
        Bias: [[-8.05024335+0.j]]
        Weight 1:   (0, 0)	(9.542149991432348+0j) 
        Weight 2:   (0, 0)	(9.542488062947367+0j)
        Bias: [[-8.05416045+0.j]]
        Weight 1:   (0, 0)	(9.546067274101945+0j) 
        Weight 2:   (0, 0)	(9.546404188545123+0j)
        Bias: [[-8.05807754+0.j]]
        Weight 1:   (0, 0)	(9.549984554887134+0j) 
        Weight 2:   (0, 0)	(9.550320316218293+0j)
        Bias: [[-8.06199464+0.j]]
        Weight 1:   (0, 0)	(9.553901833794313+0j) 
        Weight 2:   (0, 0)	(9.554236445959729+0j)
        Bias: [[-8.06591173+0.j]]
        Weight 1:   (0, 0)	(9.557819110829865+0j) 
        Weight 2:   (0, 0)	(9.558152577762305+0j)
        Bias: [[-8.06982882+0.j]]
        Weight 1:   (

KeyboardInterrupt: 

In [41]:
bias

array([[-38.51073551+0.j]])

In [35]:
print(weights.data)

  (0, 0)	(39.99879389040163+0j)
  (1, 0)	(39.998793890403+0j)


Make predictions:

In [36]:
inputs = Qobj(np.array([1,1]))

In [136]:
inputs.trans()

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 1.]]

In [137]:
result = inputs.trans() * weights + bias

In [138]:
activation(result)

array([[1.+0.j]])

In [139]:
inputs = Qobj(np.array([0,0]))

In [140]:
result = inputs.trans() * weights + bias

In [141]:
activation(result)

array([[6.02751371e-09+0.j]])

In [142]:
inputs = Qobj(np.array([0,1]))

In [143]:
result = inputs.trans() * weights + bias

In [144]:
activation(result)

array([[0.81578667+0.j]])

In [145]:
inputs = Qobj(np.array([1,0]))

In [146]:
result = inputs.trans() * weights + bias

In [147]:
activation(result)

array([[0.81578667+0.j]])